In [5]:
import pandas as pd
import numpy as np

In [2]:
dset1=pd.read_excel('final4.xlsx')

In [3]:
dset1 = dset1.dropna(axis=0)

dset1

,MicroMarket,cl_pincode,index,open_stock_units,open_stock_mnsqft,overhang,New Launch Wt Average Price (/Sqft),Wt. Average Price Absorbed unit (INR/Sft),Wt. Average Price Available unit (INR/Sft),New Launch Absorption in Units,...,christian,hindu,jain,muslim,sikh,rural,semi_urban,urban,Total Absorption in units,Total Absorption in Mn Sqft
49,Alwarpet,600018,2019Q4,0,0.00,24,15900.00,15900.000000,15900.000000,5,...,0.01,0.97,0.0,0.02,0,0,0,1,5,0.02
50,Alwarpet,600018,2020Q1,345,1.22,85,15900.00,15900.000000,15900.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,8,0.03
85,Cenotaph Road,600018,2016Q1,82,0.21,34,20000.00,20000.000000,20000.000000,5,...,0.01,0.97,0.0,0.02,0,0,0,1,8,0.02
86,Cenotaph Road,600018,2016Q2,112,0.28,49,20000.00,20000.000000,20000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,4,0.01
87,Cenotaph Road,600018,2016Q3,103,0.27,55,20000.00,20000.000000,20000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,2,0.00
88,Cenotaph Road,600018,2016Q4,97,0.24,57,20000.00,20000.000000,20000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,1,0.00
89,Cenotaph Road,600018,2017Q1,96,0.24,81,20000.00,22000.000000,21333.333333,0,...,0.01,0.97,0.0,0.02,0,0,0,1,1,0.00
90,Cenotaph Road,600018,2017Q2,93,0.24,92,20000.00,22000.000000,22000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,1,0.00
91,Cenotaph Road,600018,2017Q3,90,0.24,89,20000.00,22000.000000,22000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,1,0.00
92,Cenotaph Road,600018,2017Q4,87,0.21,87,20000.00,22000.000000,22000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,0,0.00
93,Cenotaph Road,600018,2018Q1,87,0.21,87,20000.00,22000.000000,22000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,0,0.00
94,Cenotaph Road,600018,2018Q2,87,0.21,86,20000.00,22000.000000,22000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,1,0.00
95,Cenotaph Road,600018,2018Q3,82,0.21,80,20000.00,22000.000000,22000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,2,0.00
96,Cenotaph Road,600018,2018Q4,75,0.19,72,20000.00,22000.000000,22000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,3,0.00
97,Cenotaph Road,600018,2019Q1,68,0.18,63,20000.00,22000.000000,22000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,3,0.01
98,Cenotaph Road,600018,2019Q2,57,0.15,48,20000.00,22000.000000,22000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,3,0.00
99,Cenotaph Road,600018,2019Q3,49,0.12,44,20000.00,22000.000000,22000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,2,0.00
100,Cenotaph Road,600018,2019Q4,44,0.12,39,20000.00,22000.000000,22000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,1,0.00
101,Cenotaph Road,600018,2020Q1,42,0.12,38,20000.00,22000.000000,20666.666667,0,...,0.01,0.97,0.0,0.02,0,0,0,1,0,0.00
121,Teynampet,600018,2012Q2,71,0.12,45,12000.00,12000.000000,12000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,2,0.00
122,Teynampet,600018,2012Q3,66,0.09,65,12000.00,12000.000000,12000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,1,0.00
123,Teynampet,600018,2012Q4,62,0.09,61,12000.00,12000.000000,12000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,1,0.00
124,Teynampet,600018,2013Q1,54,0.09,39,12000.00,13000.000000,13000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,4,0.00
125,Teynampet,600018,2013Q2,46,0.07,34,12000.00,13000.000000,13000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,2,0.00
126,Teynampet,600018,2013Q3,42,0.06,32,12000.00,13000.000000,13000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,0,0.00
127,Teynampet,600018,2013Q4,38,0.06,23,12000.00,13000.000000,13000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,5,0.00
128,Teynampet,600018,2014Q1,22,0.03,12,12000.00,13000.000000,13000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,4,0.00
129,Teynampet,600018,2014Q2,13,0.02,7,12000.00,13000.000000,13000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,3,0.00
130,Teynampet,600018,2014Q3,3,0.00,1,12000.00,13000.000000,13000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,2,0.00
131,Teynampet,600018,2014Q4,0,0.00,0,12000.00,13000.000000,13000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8436,Kolapakkam,600074,2012Q4,353,0.39,34,5000.00,4917.333333,4822.000000,25,...,0.03,0.92,0.0,0.05,0,0,0,1,63,0.09
8437,Kolapakkam,600074,2013Q1,307,0.33,28,5000.00,4954.000000,4832.000000,0,...,0.03,0.92,0.0,0.05,0,0,0,1,20,0.03
8438,Kolapakkam,600074,2013Q2,323,0.33,33,3800.00,4243.000000,4620.333333,5,...,0.03,0.92,0.0,0.05,0,0,0,1,17,0.01
8439,Kolapakkam,600074,2013Q3,318,0.32,33,3800.00,4591.666667,4670.000000,0,...,0.03,0.92,0.0,0.05,0,0,0,1,12,0.00
8440,Kolapakkam,600074,2013Q4,286,0.28,50,3800.00,4432.666667,4710.333333,0,...,0.03,0.92,0.0,0.05,0,0,0,1,8,0.00
8441,Kolapakkam,600074,2014Q1,262,0.26,73,4843.77,4610.000000,4721.666667,6,...,0.03,0.92,0.0,0.05,0,0,0,1,12,0.01
8442,Kolapakkam,600074,2014Q2,362,0.37,114,4440.00,4651.333333,4716.666667,24,...,0.03,0.92,0.0,0.05,0,0,0,1,39,0.03
8443,Kolapakkam,600074,2014Q3,843,0.81,94,4440.00,4519.333333,4595.000000,0,...,0.03,0.92,0.0,0.05,0,0,0,1,56,0.06
8444,Kolapakkam,600074,2014Q4,694,0.67,58,4440.00,4605.666667,4632.333333,0,...,0.03,0.92,0.0,0.05,0,0,0,1,39,0.03
8445,Kolapakkam,600074,2015Q1,592,0.57,43,4440.00,4582.000000,4661.333333,0,...,0.03,0.92,0.0,0.05,0,0,0,1,26,0.03
8446,Kolapakkam,600074,2015Q2,583,0.59,44,4800.00,4723.666667,4707.666667,10,...,0.03,0.92,0.0,0.05,0,0,0,1,40,0.04
8447,Kolapakkam,600074,2015Q3,606,0.63,52,5500.00,4871.666667,4817.666667,9,...,0.03,0.92,0.0,0.05,0,0,0,1,42,0.05
8448,Kolapakkam,600074,2015Q4,687,0.85,55,5500.00,5202.333333,4994.000000,0,...,0.03,0.92,0.0,0.05,0,0,0,1,33,0.05
8449,Kolapakkam,600074,2016Q1,1434,1.74,110,5074.75,5082.666667,5043.000000,43,...,0.03,0.92,0.0,0.05,0,0,0,1,101,0.13
8450,Kolapakkam,600074,2016Q2,1659,1.97,80,5074.75,5221.666667,5007.000000,0,...,0.03,0.92,0.0,0.05,0,0,0,1,71,0.10
8451,Kolapakkam,600074,2016Q3,1431,1.69,60,5074.75,5034.666667,5021.000000,0,...,0.03,0.92,0.0,0.05,0,0,0,1,80,0.09
8452,Kolapakkam,600074,2016Q4,1216,1.44,49,5074.75,4964.333333,5029.333333,0,...,0.03,0.92,0.0,0.05,0,0,0,1,42,0.05
8453,Kolapakkam,600074,2017Q1,1110,1.32,53,5074.75,4837.000000,5056.333333,0,...,0.03,0.92,0.0,0.05,0,0,0,1,33,0.03
8454,Kolapakkam,600074,2017Q2,1013,1.22,57,5074.75,4696.333333,5126.333333,0,...,0.03,0.92,0.0,0.05,0,0,0,1,37,0.04
8455,Kolapakkam,600074,2017Q3,949,1.19,74,6440.00,5251.333333,5311.333333,4,...,0.03,0.92,0.0,0.05,0,0,0,1,31,0.04
8456,Kolapakkam,600074,2017Q4,923,1.22,78,6440.00,5085.333333,5401.666667,0,...,0.03,0.92,0.0,0.05,0,0,0,1,41,0.05
8457,Kolapakkam,600074,2018Q1,918,1.20,70,5628.00,5260.000000,5381.666667,6,...,0.03,0.92,0.0,0.05,0,0,0,1,76,0.09
8458,Kolapakkam,600074,2018Q2,999,1.27,64,4600.00,4920.666667,5293.000000,5,...,0.03,0.92,0.0,0.05,0,0,0,1,48,0.05
8459,Kolapakkam,600074,2018Q3,1064,1.35,59,5000.00,4865.333333,5252.333333,2,...,0.03,0.92,0.0,0.05,0,0,0,1,59,0.06
8460,Kolapakkam,600074,2018Q4,1018,1.33,48,6440.00,5085.666667,5419.333333,1,...,0.03,0.92,0.0,0.05,0,0,0,1,69,0.08
8461,Kolapakkam,600074,2019Q1,855,1.15,40,6440.00,4978.000000,5492.666667,0,...,0.03,0.92,0.0,0.05,0,0,0,1,57,0.06
8462,Kolapakkam,600074,2019Q2,711,0.99,36,6440.00,4812.333333,5577.666667,0,...,0.03,0.92,0.0,0.05,0,0,0,1,31,0.03
8463,Kolapakkam,600074,2019Q3,631,0.90,37,6440.00,4882.333333,5639.666667,0,...,0.03,0.92,0.0,0.05,0,0,0,1,22,0.03
8464,Kolapakkam,600074,2019Q4,560,0.82,45,6440.00,4798.000000,5733.333333,0,...,0.03,0.92,0.0,0.05,0,0,0,1,23,0.03
8465,Kolapakkam,600074,2020Q1,486,0.74,51,6440.00,5319.333333,5799.666667,0,...,0.03,0.92,0.0,0.05,0,0,0,1,20,0.02

In [4]:
X = dset1.iloc[:,3:-2]

#X = X.drop(columns='Total Absorption in units')
X

,open_stock_units,open_stock_mnsqft,overhang,New Launch Wt Average Price (/Sqft),Wt. Average Price Absorbed unit (INR/Sft),Wt. Average Price Available unit (INR/Sft),New Launch Absorption in Units,New Launch Absorption in Mn Sqft,Unsold in units,Unsold in Mn Sqft,...,traffic_junctions,buddhist,christian,hindu,jain,muslim,sikh,rural,semi_urban,urban
49,0,0.00,24,15900.00,15900.000000,15900.000000,5,0.02,119,0.42,...,0,0,0.01,0.97,0.0,0.02,0,0,0,1
50,345,1.22,85,15900.00,15900.000000,15900.000000,0,0.00,337,1.19,...,0,0,0.01,0.97,0.0,0.02,0,0,0,1
85,82,0.21,34,20000.00,20000.000000,20000.000000,5,0.01,121,0.31,...,0,0,0.01,0.97,0.0,0.02,0,0,0,1
86,112,0.28,49,20000.00,20000.000000,20000.000000,0,0.00,108,0.27,...,0,0,0.01,0.97,0.0,0.02,0,0,0,1
87,103,0.27,55,20000.00,20000.000000,20000.000000,0,0.00,101,0.26,...,0,0,0.01,0.97,0.0,0.02,0,0,0,1
88,97,0.24,57,20000.00,20000.000000,20000.000000,0,0.00,96,0.24,...,0,0,0.01,0.97,0.0,0.02,0,0,0,1
89,96,0.24,81,20000.00,22000.000000,21333.333333,0,0.00,95,0.24,...,0,0,0.01,0.97,0.0,0.02,0,0,0,1
90,93,0.24,92,20000.00,22000.000000,22000.000000,0,0.00,92,0.24,...,0,0,0.01,0.97,0.0,0.02,0,0,0,1
91,90,0.24,89,20000.00,22000.000000,22000.000000,0,0.00,89,0.23,...,0,0,0.01,0.97,0.0,0.02,0,0,0,1
92,87,0.21,87,20000.00,22000.000000,22000.000000,0,0.00,87,0.21,...,0,0,0.01,0.97,0.0,0.02,0,0,0,1
93,87,0.21,87,20000.00,22000.000000,22000.000000,0,0.00,87,0.21,...,0,0,0.01,0.97,0.0,0.02,0,0,0,1
94,87,0.21,86,20000.00,22000.000000,22000.000000,0,0.00,86,0.21,...,0,0,0.01,0.97,0.0,0.02,0,0,0,1
95,82,0.21,80,20000.00,22000.000000,22000.000000,0,0.00,80,0.21,...,0,0,0.01,0.97,0.0,0.02,0,0,0,1
96,75,0.19,72,20000.00,22000.000000,22000.000000,0,0.00,72,0.18,...,0,0,0.01,0.97,0.0,0.02,0,0,0,1
97,68,0.18,63,20000.00,22000.000000,22000.000000,0,0.00,65,0.17,...,0,0,0.01,0.97,0.0,0.02,0,0,0,1
98,57,0.15,48,20000.00,22000.000000,22000.000000,0,0.00,54,0.14,...,0,0,0.01,0.97,0.0,0.02,0,0,0,1
99,49,0.12,44,20000.00,22000.000000,22000.000000,0,0.00,47,0.12,...,0,0,0.01,0.97,0.0,0.02,0,0,0,1
100,44,0.12,39,20000.00,22000.000000,22000.000000,0,0.00,43,0.12,...,0,0,0.01,0.97,0.0,0.02,0,0,0,1
101,42,0.12,38,20000.00,22000.000000,20666.666667,0,0.00,42,0.12,...,0,0,0.01,0.97,0.0,0.02,0,0,0,1
121,71,0.12,45,12000.00,12000.000000,12000.000000,0,0.00,69,0.11,...,0,0,0.01,0.97,0.0,0.02,0,0,0,1
122,66,0.09,65,12000.00,12000.000000,12000.000000,0,0.00,65,0.09,...,0,0,0.01,0.97,0.0,0.02,0,0,0,1
123,62,0.09,61,12000.00,12000.000000,12000.000000,0,0.00,61,0.09,...,0,0,0.01,0.97,0.0,0.02,0,0,0,1
124,54,0.09,39,12000.00,13000.000000,13000.000000,0,0.00,50,0.09,...,0,0,0.01,0.97,0.0,0.02,0,0,0,1
125,46,0.07,34,12000.00,13000.000000,13000.000000,0,0.00,44,0.06,...,0,0,0.01,0.97,0.0,0.02,0,0,0,1
126,42,0.06,32,12000.00,13000.000000,13000.000000,0,0.00,42,0.06,...,0,0,0.01,0.97,0.0,0.02,0,0,0,1
127,38,0.06,23,12000.00,13000.000000,13000.000000,0,0.00,33,0.05,...,0,0,0.01,0.97,0.0,0.02,0,0,0,1
128,22,0.03,12,12000.00,13000.000000,13000.000000,0,0.00,18,0.03,...,0,0,0.01,0.97,0.0,0.02,0,0,0,1
129,13,0.02,7,12000.00,13000.000000,13000.000000,0,0.00,10,0.01,...,0,0,0.01,0.97,0.0,0.02,0,0,0,1
130,3,0.00,1,12000.00,13000.000000,13000.000000,0,0.00,1,0.00,...,0,0,0.01,0.97,0.0,0.02,0,0,0,1
131,0,0.00,0,12000.00,13000.000000,13000.000000,0,0.00,0,0.00,...,0,0,0.01,0.97,0.0,0.02,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8436,353,0.39,34,5000.00,4917.333333,4822.000000,25,0.03,374,0.42,...,0,0,0.03,0.92,0.0,0.05,0,0,0,1
8437,307,0.33,28,5000.00,4954.000000,4832.000000,0,0.00,287,0.31,...,0,0,0.03,0.92,0.0,0.05,0,0,0,1
8438,323,0.33,33,3800.00,4243.000000,4620.333333,5,0.00,343,0.34,...,0,0,0.03,0.92,0.0,0.05,0,0,0,1
8439,318,0.32,33,3800.00,4591.666667,4670.000000,0,0.00,306,0.31,...,0,0,0.03,0.92,0.0,0.05,0,0,0,1
8440,286,0.28,50,3800.00,4432.666667,4710.333333,0,0.00,278,0.27,...,0,0,0.03,0.92,0.0,0.05,0,0,0,1
8441,262,0.26,73,4843.77,4610.000000,4721.666667,6,0.01,297,0.30,...,0,0,0.03,0.92,0.0,0.05,0,0,0,1
8442,362,0.37,114,4440.00,4651.333333,4716.666667,24,0.02,539,0.53,...,0,0,0.03,0.92,0.0,0.05,0,0,0,1
8443,843,0.81,94,4440.00,4519.333333,4595.000000,0,0.00,787,0.76,...,0,0,0.03,0.92,0.0,0.05,0,0,0,1
8444,694,0.67,58,4440.00,4605.666667,4632.333333,0,0.00,655,0.63,...,0,0,0.03,0.92,0.0,0.05,0,0,0,1
8445,592,0.57,43,4440.00,4582.000000,4661.333333,0,0.00,566,0.55,...,0,0,0.03,0.92,0.0,0.05,0,0,0,1
8446,583,0.59,44,4800.00,4723.666667,4707.666667,10,0.01,615,0.63,...,0,0,0.03,0.92,0.0,0.05,0,0,0,1
8447,606,0.63,52,5500.00,4871.666667,4817.666667,9,0.02,634,0.71,...,0,0,0.03,0.92,0.0,0.05,0,0,0,1
8448,687,0.85,55,5500.00,5202.333333,4994.000000,0,0.00,654,0.80,...,0,0,0.03,0.92,0.0,0.05,0,0,0,1
8449,1434,1.74,110,5074.75,5082.666667,5043.000000,43,0.05,1800,2.18,...,0,0,0.03,0.92,0.0,0.05,0,0,0,1
8450,1659,1.97,80,5074.75,5221.666667,5007.000000,0,0.00,1588,1.88,...,0,0,0.03,0.92,0.0,0.05,0,0,0,1
8451,1431,1.69,60,5074.75,5034.666667,5021.000000,0,0.00,1351,1.59,...,0,0,0.03,0.92,0.0,0.05,0,0,0,1
8452,1216,1.44,49,5074.75,4964.333333,5029.333333,0,0.00,1174,1.39,...,0,0,0.03,0.92,0.0,0.05,0,0,0,1
8453,1110,1.32,53,5074.75,4837.000000,5056.333333,0,0.00,1077,1.29,...,0,0,0.03,0.92,0.0,0.05,0,0,0,1
8454,1013,1.22,57,5074.75,4696.333333,5126.333333,0,0.00,976,1.18,...,0,0,0.03,0.92,0.0,0.05,0,0,0,1
8455,949,1.19,74,6440.00,5251.333333,5311.333333,4,0.01,956,1.23,...,0,0,0.03,0.92,0.0,0.05,0,0,0,1
8456,923,1.22,78,6440.00,5085.333333,5401.666667,0,0.00,882,1.17,...,0,0,0.03,0.92,0.0,0.05,0,0,0,1
8457,918,1.20,70,5628.00,5260.000000,5381.666667,6,0.01,988,1.27,...,0,0,0.03,0.92,0.0,0.05,0,0,0,1
8458,999,1.27,64,4600.00,4920.666667,5293.000000,5,0.01,1023,1.30,...,0,0,0.03,0.92,0.0,0.05,0,0,0,1
8459,1064,1.35,59,5000.00,4865.333333,5252.333333,2,0.00,1040,1.32,...,0,0,0.03,0.92,0.0,0.05,0,0,0,1
8460,1018,1.33,48,6440.00,5085.666667,5419.333333,1,0.00,976,1.30,...,0,0,0.03,0.92,0.0,0.05,0,0,0,1
8461,855,1.15,40,6440.00,4978.000000,5492.666667,0,0.00,798,1.08,...,0,0,0.03,0.92,0.0,0.05,0,0,0,1
8462,711,0.99,36,6440.00,4812.333333,5577.666667,0,0.00,680,0.96,...,0,0,0.03,0.92,0.0,0.05,0,0,0,1
8463,631,0.90,37,6440.00,4882.333333,5639.666667,0,0.00,609,0.87,...,0,0,0.03,0.92,0.0,0.05,0,0,0,1
8464,560,0.82,45,6440.00,4798.000000,5733.333333,0,0.00,537,0.80,...,0,0,0.03,0.92,0.0,0.05,0,0,0,1
8465,486,0.74,51,6440.00,5319.333333,5799.666667,0,0.00,466,0.71,...,0,0,0.03,0.92,0.0,0.05,0,0,0,1

In [5]:
y = dset1.iloc[:,-2]
y

49        5
50        8
85        8
86        4
87        2
88        1
89        1
90        1
91        1
92        0
93        0
94        1
95        2
96        3
97        3
98        3
99        2
100       1
101       0
121       2
122       1
123       1
124       4
125       2
126       0
127       5
128       4
129       3
130       2
131       0
       ...
8436     63
8437     20
8438     17
8439     12
8440      8
8441     12
8442     39
8443     56
8444     39
8445     26
8446     40
8447     42
8448     33
8449    101
8450     71
8451     80
8452     42
8453     33
8454     37
8455     31
8456     41
8457     76
8458     48
8459     59
8460     69
8461     57
8462     31
8463     22
8464     23
8465     20
Name: Total Absorption in units, Length: 6565, dtype: int64

In [6]:
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression

In [7]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()


X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 0)

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

linreg = LinearRegression().fit(X_train_scaled, y_train)

print('linear model coeff (w): {}'
     .format(linreg.coef_))
print('linear model intercept (b): {:.3f}'
     .format(linreg.intercept_))
print('R-squared score (training): {:.3f}'
     .format(linreg.score(X_train_scaled, y_train)))
print('R-squared score (test): {:.3f}'
     .format(linreg.score(X_test_scaled, y_test)))

linear model coeff (w): [ 8.19000000e+03 -1.50976120e-10  1.13686838e-12 -8.64019967e-12
  7.73070497e-12  1.50066626e-11  5.68434189e-12  1.13686838e-11
 -8.48700000e+03  1.09025677e-10  1.87800000e+03  1.45000000e+03
  8.25000000e+02  4.90000000e+02  3.80000000e+02  3.46000000e+02
  1.14000000e+03  1.96000000e+02  4.57000000e+02  1.95541361e-11
 -7.61701813e-12 -1.13686838e-11 -6.13908924e-12 -2.19984031e-11
 -2.45563569e-11  2.61337618e-11  3.75166564e-12 -1.53477231e-11
  1.21644916e-11 -2.75122147e-11 -7.10542736e-12  1.20508048e-11
 -1.81614723e-11  5.96855898e-12 -1.27116095e-11  1.67688086e-12
  2.18847163e-12 -1.20508048e-11  3.12070370e-11  2.89901436e-12
 -2.33058017e-12  2.70929945e-11 -9.66338121e-13 -1.26672006e-11
 -3.33955086e-12  6.82121026e-13 -4.73391992e-10 -3.89363208e-10
 -2.55738541e-10 -1.55907287e-10 -1.51644031e-10 -9.16742238e-11
 -2.87087687e-10 -4.65689709e-11 -1.65201186e-10  1.84456894e-11
 -6.82121026e-12 -2.69437805e-11  1.65982783e-11  1.69109171e-12
  1.46087586e-11  4.15099066e-11 -3.78008735e-12  1.49498192e-11
  1.63709046e-11 -1.20508048e-11  5.45696821e-12  8.35598257e-12
 -3.92219590e-12  1.13686838e-12  4.26325641e-12  2.16004992e-12
 -2.08899564e-12 -2.38742359e-11  1.34718903e-11  9.09494702e-13
 -8.18545232e-12  2.38742359e-12 -1.42819090e-12 -6.72173428e-12
 -2.72848411e-12  2.78532752e-12  4.77484718e-12 -2.10320650e-12
  2.98427949e-12  2.23110419e-12 -2.14015472e-11 -2.91606739e-11
 -4.68958206e-12  2.99280600e-11 -1.44382284e-11  9.09494702e-13
  2.09752216e-11 -2.76685341e-11 -5.43138867e-11 -3.72324394e-12
  1.53477231e-12  4.58584282e-11  7.20490334e-12 -1.03739239e-12
 -3.63797881e-12  1.40119027e-11 -5.08464382e-11  9.20863386e-12
  1.83035809e-11  3.26281224e-11 -2.88480351e-11 -4.43378667e-12
  1.71951342e-11  1.39266376e-12  4.99085218e-11 -4.27746727e-12
  6.32383035e-12 -6.10214101e-11 -3.87956334e-11 -9.94759830e-13
  4.40536496e-12  2.62616595e-11 -1.14397380e-11 -4.83169060e-13
  2.39452902e-12 -1.04307674e-11 -1.22213351e-12  1.16529009e-12
 -2.30215846e-12 -4.98232566e-11 -1.62145852e-11 -3.42339490e-11
  3.90087962e-11  4.01030320e-11 -7.07700565e-12  1.24487087e-11
  2.10320650e-11 -9.12336873e-12 -7.34701189e-12  1.09423581e-12
  1.36708422e-11 -5.81223958e-12  2.25064412e-11  1.26334498e-11
 -8.29913915e-12  2.03890238e-11  1.74793513e-11 -1.71667125e-11
  1.15960574e-11  2.93596258e-11  6.73594514e-12 -1.81330506e-11
  3.54134500e-11 -3.31681349e-11  7.04858394e-12  1.37845291e-11
  2.81659140e-11  2.27018404e-11 -2.55795385e-13  2.07478479e-11
  1.45377044e-11 -2.38173925e-11 -1.22213351e-11  7.38964445e-13
  7.29016847e-12 -8.35598257e-12  2.61906052e-11 -7.94386779e-12
 -6.22151219e-11  5.44844170e-11 -3.84829946e-11  5.85487214e-12
 -1.68256520e-11  6.50857146e-12  0.00000000e+00 -1.36424205e-11
  1.41540113e-11 -2.12594387e-11  2.38742359e-12  2.67732503e-11
  1.10844667e-12  0.00000000e+00 -1.02318154e-12  0.00000000e+00
 -6.70752343e-12  0.00000000e+00  0.00000000e+00  6.49436060e-12
  0.00000000e+00 -1.21502808e-11  9.66338121e-13  1.22497568e-11
  6.82121026e-12 -1.09423581e-11  5.79802872e-12  1.35571554e-11
 -1.67119651e-11  4.20641300e-12  1.59730007e-11  2.04636308e-12
 -1.06581410e-11 -1.35287337e-11 -1.99520400e-11 -8.69704309e-12
  5.45696821e-12 -2.04636308e-12 -5.91171556e-12 -3.04112291e-11
 -4.56452653e-11  1.38697942e-11 -4.54747351e-12  2.93312041e-11
 -5.91171556e-12  7.00310920e-11 -3.47881723e-11 -1.26902933e-11
  1.03739239e-11 -2.71143108e-11 -2.09183781e-11  6.19593266e-12
  2.74269496e-11  2.62616595e-11  2.04636308e-12 -1.87583282e-12
 -2.61479727e-11  0.00000000e+00  0.00000000e+00  2.95585778e-12
  1.73940862e-11 -2.13731255e-11  1.70530257e-12  0.00000000e+00
  0.00000000e+00  0.00000000e+00 -8.07176548e-12 -9.49285095e-12
 -8.00071120e-12  0.00000000e+00  0.00000000e+00  5.00222086e-12
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  9.37916411e-13  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00 -2.27373675e-12 -4.54747351e-13 -2.52384780e-11
  3.86535248e-12  0.00000000e+00  2.63753464e-11  2.41016096e-11
  2.45563569e-11]
linear model intercept (b): 0.000
R-squared score (training): 1.000
R-squared score (test): 1.000

In [8]:
coeff_df = pd.DataFrame(linreg.coef_,X.columns,columns=['Coefficient'])
coeff_df.sort_values(by=['Coefficient'],ascending=False).head(10)

                     Coefficient
open_stock_units          8190.0
tsw_new_units_<=30        1878.0
tsw_new_units_30-40       1450.0
tsw_new_units_80-90       1140.0
tsw_new_units_40-50        825.0
tsw_new_units_50-60        490.0
tsw_new_units_>1           457.0
tsw_new_units_60-70        380.0
tsw_new_units_70-80        346.0
tsw_new_units_90-1         196.0

In [9]:
from sklearn.linear_model import Ridge
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                   random_state = 0)

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

linridge = Ridge(alpha=0.0).fit(X_train_scaled, y_train)

print('ridge regression linear model intercept: {}'
     .format(linridge.intercept_))
print('ridge regression linear model coeff:\n{}'
     .format(linridge.coef_))
print('R-squared score (training): {:.3f}'
     .format(linridge.score(X_train_scaled, y_train)))
print('R-squared score (test): {:.3f}'
     .format(linridge.score(X_test_scaled, y_test)))
print('Number of non-zero features: {}'
     .format(np.sum(linridge.coef_ != 0)))

ridge regression linear model intercept: 160.590009462464
ridge regression linear model coeff:
[ 8.19000000e+03 -1.61733738e-10 -1.95399252e-12 -1.20046195e-11
  5.20472554e-12  1.09405818e-11  1.06723519e-11  3.35198536e-12
 -8.48700000e+03  1.10709664e-10  1.87800000e+03  1.45000000e+03
  8.25000000e+02  4.90000000e+02  3.80000000e+02  3.46000000e+02
  1.14000000e+03  1.96000000e+02  4.57000000e+02  1.24273924e-11
 -9.84101689e-12 -1.54471991e-11 -5.27933253e-12 -2.14583906e-11
 -2.55244714e-11  1.30739863e-11  4.94537744e-12 -1.53690394e-11
  1.03597131e-11 -2.89226421e-11 -1.13313803e-11  1.17603705e-11
 -1.76361148e-11  6.52278231e-12 -1.21929133e-11  4.01456646e-13
  1.30739863e-12 -1.24629196e-11  3.30970806e-11  7.49089679e-12
 -1.67932335e-12  2.47055709e-11 -4.26325641e-13 -1.16671117e-11
 -1.06403775e-12  3.74811293e-13 -4.51450433e-10 -3.70960151e-10
 -2.46103582e-10 -1.48759227e-10 -1.43813850e-10 -8.67430572e-11
 -2.73900014e-10 -4.27036184e-11 -1.57399427e-10  1.75930381e-11
 -8.04334377e-12 -2.44249065e-11  1.78737025e-11  1.85451654e-12
  1.32409639e-11  4.11972678e-11 -4.98090458e-12  1.32871492e-11
  1.51381130e-11 -1.31805677e-11  5.40012479e-12  9.89075488e-12
 -3.13882254e-12  3.55271368e-12  3.36797257e-12  2.03215222e-12
 -2.98427949e-12 -2.29931629e-11  1.29354305e-11 -1.39976919e-12
 -8.29913915e-12  3.18678417e-12 -1.66267000e-12 -3.78008735e-12
 -2.33768560e-12  1.37490019e-12  2.72779528e+00  3.00661326e+02
  2.99286303e+01  1.79651462e+02  6.84235944e+01 -5.56258325e+01
  1.20647083e+00 -3.38860627e-01  1.43910126e+02  2.67378902e+02
  4.10612690e+01  3.02977267e+02  9.65282412e+00 -1.39748734e+01
  2.63193175e+02 -2.21078015e+02 -1.58473449e+02 -2.99512646e+02
 -3.59864891e+02  5.94473113e+01 -3.64307270e+02  5.15109658e+02
  2.20366297e+01  1.91490372e+02  4.83862019e+01  2.70157639e+01
 -3.87465270e+02  5.14967909e+02  3.37963619e+02  2.21691990e+02
  2.86469855e+02 -1.28560691e+02 -2.75168765e+02  1.53195872e+02
 -4.94378849e+01 -7.08357018e+00 -3.51351353e+02 -8.63831327e+01
 -1.22272478e+02 -1.98309471e+02 -9.26820626e+00  6.61215532e+02
 -1.86337677e+02  3.21338561e+02  6.27618051e+01 -1.94026244e+02
 -5.81890827e+01  1.45515906e+01 -2.22183266e+02  1.07942927e+02
 -3.70361376e+01  2.29615493e+02 -1.70009757e+02 -1.91525336e+02
 -3.70025389e+02  6.07819011e+01  2.46725596e+02  4.73232768e+01
 -2.14422164e+02  3.71142892e+02  3.13160653e+01 -3.23362769e+02
  2.04853396e+02  1.21519433e+02 -7.15516176e+01  1.11473850e+01
  4.11515269e+01 -1.01568532e+02  2.77472880e+01 -4.32188065e+02
 -5.12037536e+02 -5.94619428e+02  1.03039017e+02  5.01651887e+02
  4.41989467e+01 -7.59362506e+01  2.90818813e+00 -3.01096617e+01
 -2.79191678e+02  9.04424902e-01 -7.44557530e+01 -8.39889434e+01
  3.70276134e+02 -3.53789210e+02 -4.28430367e+01  3.45210513e+02
 -2.35514223e+02  1.54408676e+02  2.50956167e+02  3.30392176e+01
  7.75305611e+01 -1.09714339e+02 -7.00974239e+01  1.68779301e+01
 -2.25003142e+01 -7.06144820e+01 -3.28150245e+01 -2.99452395e-01
 -9.98151793e-02  9.36851662e+01  8.33113492e+01 -4.85765184e+01
 -4.23225175e+01 -4.58862398e+01  1.48893014e+01  5.35813535e+01
  1.57064634e+01 -1.14836191e+01  2.53206972e+01  1.27465355e+00
 -1.06600177e+01  7.11677839e+00 -5.12131251e+01  2.61262224e+00
  1.72702225e+02 -3.33425479e+01  4.34823942e+00 -2.32684133e+02
  2.78591732e+01  1.68204943e+01 -2.83757422e+01  3.34038610e+02
  1.22124724e+02 -7.37648537e+00  4.64104879e+01 -6.73001882e+01
 -6.06791419e+01  1.37314130e+02 -7.60000884e+01 -5.07551451e+01
  3.13894527e+01  4.63582123e+01  2.13984116e+02 -2.34559918e+02
 -5.38799719e+01  1.12112805e+02  1.45918483e+01 -6.25972718e+02
 -1.39887126e+02 -1.11935593e+02  2.20093863e+01  3.51056690e+01
 -8.81020769e+00 -9.99184663e+01 -3.39791109e+01  4.27452087e+01
  1.30779631e+02  2.78973550e+01  1.24807895e+01  1.27187935e+01
 -2.27251278e+01 -4.26364695e+01  1.78707611e+02  1.65153712e+01
 -1.22851422e+02  1.54616459e+01  2.31695474e+02 -3.96971069e+00
  1.95533728e-01 -2.52673431e+01 -2.70775145e+01 -8.96392118e+01
  3.30346299e+01 -9.01621032e+00  5.75406593e+00 -3.95057871e+01
 -1.08104467e+00 -1.25147585e+01 -1.59949817e+02 -1.55032242e+02
 -1.61367462e+02]
R-squared score (training): 1.000
R-squared score (test): 1.000
Number of non-zero features: 253

In [10]:
coeff_df = pd.DataFrame(linridge.coef_,X.columns,columns=['Coefficient'])
coeff_df.sort_values(by=['Coefficient'],ascending=False).head(10)

                     Coefficient
open_stock_units     8190.000000
tsw_new_units_<=30   1878.000000
tsw_new_units_30-40  1450.000000
tsw_new_units_80-90  1140.000000
tsw_new_units_40-50   825.000000
TOT_M                 661.215532
mcouple_one           515.109658
avail_bank_srv        514.967909
MARGWORK_M            501.651887
tsw_new_units_50-60   490.000000

In [11]:
from sklearn.linear_model import Lasso

linlasso = Lasso(alpha=0.1, max_iter = 10000).fit(X_train_scaled, y_train)
print('lasso regression linear model intercept: {}'
     .format(linlasso.intercept_))
print('lasso regression linear model coeff:\n{}'
     .format(linlasso.coef_))
print('Non-zero features: {}'
     .format(np.sum(linlasso.coef_ != 0)))
print('R-squared score (training): {:.3f}'
     .format(linlasso.score(X_train_scaled, y_train)))
print('R-squared score (test): {:.3f}\n'
     .format(linlasso.score(X_test_scaled, y_test)))
print('Features with non-zero weight (sorted by absolute magnitude):')

for e in sorted (list(zip(list(X), linlasso.coef_)),
                key = lambda e: -abs(e[1])):
    if e[1] != 0:
        print('\t{}, {:.3f}'.format(e[0], e[1]))

lasso regression linear model intercept: -257.35690545790175
lasso regression linear model coeff:
[  0.           0.          -0.64038128  -0.          -0.
  -0.           0.           0.           0.          34.92081707
   0.           0.           0.           0.           0.
   0.           0.           0.           0.           0.
   0.           0.           0.           0.           0.
   0.           0.           0.           0.           0.
   0.          22.63033092   0.           0.           0.
   0.           4.79454881   0.           0.           0.
   0.           0.           0.           0.           0.
   0.         570.5506714  430.05181088 347.43470921 177.68195094
 170.37777149  76.13508474   0.          50.09891391  91.27459567
   0.           0.           0.           0.           0.
   0.           0.           0.          80.18212944  -0.
   0.           0.           0.           0.           0.
   8.96649237   0.           0.          -0.           0.
   0.           0.           0.           0.           0.
   0.           0.           0.           0.           0.
   0.           0.           0.           0.           0.
   0.           0.           0.           0.           0.
   0.           0.           0.           0.           0.
   0.           0.           0.           0.           0.
   0.           0.          -0.           0.           0.
  -0.           0.          -0.           0.           0.
   0.           0.           0.           0.          -0.
  -0.           0.           0.           0.           0.
   0.           0.           0.           0.           0.
   0.           0.           0.           0.           0.
   0.           0.           0.           0.           0.
   0.           0.          -0.          -0.          -0.
  -0.          -0.          -0.           0.           0.
   0.           0.           0.           0.           0.
   0.           0.          -0.          -0.          -0.
   0.           0.           0.           0.           0.
   0.           0.           0.           0.           0.
   0.           0.           0.          -0.           0.
  -0.           0.           0.           0.           0.
  -0.           0.           0.           0.           0.
   0.           0.           0.          -0.           0.
  -0.           0.          -0.          -0.          -0.
  -0.           0.          -0.           0.           0.
  -0.           0.           0.           0.           0.
  -0.          -0.          -0.           0.           0.
   0.           0.           0.          -0.          -0.
  -0.           0.          -0.          -0.           0.
  -0.           0.           0.          -0.           0.
  -0.          -0.           0.           0.           0.
   0.           0.           0.           0.           0.
  -0.           0.           0.           0.           0.
   0.           0.           0.           0.           0.
   0.           0.           0.           0.           0.
  -0.          -0.           0.        ]
Non-zero features: 14
R-squared score (training): 0.986
R-squared score (test): 0.989

Features with non-zero weight (sorted by absolute magnitude):
	tsw_ta_units_<=30, 570.551
	tsw_ta_units_30-40, 430.052
	tsw_ta_units_40-50, 347.435
	tsw_ta_units_50-60, 177.682
	tsw_ta_units_60-70, 170.378
	tsw_ta_units_>1, 91.275
	tsw_ta_mnsqft_>1, 80.182
	tsw_ta_units_70-80, 76.135
	tsw_ta_units_90-1, 50.099
	Unsold in Mn Sqft, 34.921
	new_abs_units_50-60, 22.630
	tsw_un_units_80-90, 8.966
	new_abs_units_>1, 4.795
	overhang, -0.640

In [12]:
coeff_df = pd.DataFrame(linlasso.coef_,X.columns,columns=['Coefficient'])
coeff_df.sort_values(by=['Coefficient'],ascending=False)

                         Coefficient
tsw_ta_units_<=30         570.550671
tsw_ta_units_30-40        430.051811
tsw_ta_units_40-50        347.434709
tsw_ta_units_50-60        177.681951
tsw_ta_units_60-70        170.377771
tsw_ta_units_>1            91.274596
tsw_ta_mnsqft_>1           80.182129
tsw_ta_units_70-80         76.135085
tsw_ta_units_90-1          50.098914
Unsold in Mn Sqft          34.920817
new_abs_units_50-60        22.630331
tsw_un_units_80-90          8.966492
new_abs_units_>1            4.794549
restaurant_rs_0_500         0.000000
rest_abv_4.5               -0.000000
rest_3.5_4.5                0.000000
rest_2.5_3.5                0.000000
rest_blw_2.5                0.000000
restaurant_rs_1500_3000     0.000000
restaurant_rs_500_1500     -0.000000
BPL_count                   0.000000
restaurant_rs_3000_5000     0.000000
NON_WORK_M                  0.000000
Airport                     0.000000
Commercial_area            -0.000000
Commercial_Complex          0.000000
Forest                      0.000000
Industry                    0.000000
Other                       0.000000
Parks_Play_Grounds          0.000000
...                              ...
mcouple_one                 0.000000
mcouple_none                0.000000
status_other                0.000000
tsw_un_mnsqft_50-60         0.000000
tsw_un_mnsqft_60-70         0.000000
tsw_un_mnsqft_70-80         0.000000
tsw_un_mnsqft_80-90         0.000000
tsw_un_mnsqft_90-1          0.000000
tsw_un_mnsqft_>1            0.000000
age                         0.000000
hh_tot                      0.000000
hh_good                     0.000000
hh_liv                      0.000000
hh_dilap                    0.000000
RF_other                    0.000000
rf_bt_brick                 0.000000
rf_stone_sl                 0.000000
rf_metal_asb                0.000000
rf_con                      0.000000
hh_size_one                 0.000000
hh_size_two                 0.000000
hh_size_three               0.000000
hh_size_four                0.000000
hh_size_five                0.000000
hh_size_six_eight           0.000000
hh_size_nine_plus           0.000000
status_owned                0.000000
status_rented               0.000000
urban                       0.000000
overhang                   -0.640381

[253 rows x 1 columns]

In [13]:
from sklearn.ensemble import RandomForestRegressor

clf = RandomForestRegressor(max_features=50, random_state=0).fit(X_train, y_train)
print('Accuracy of RF classifier on training set: {:.2f}'
     .format(clf.score(X_train, y_train)))
print('Accuracy of RF classifier on test set: {:.2f}'
     .format(clf.score(X_test, y_test)))

Accuracy of RF classifier on training set: 0.98
Accuracy of RF classifier on test set: 0.95

In [14]:
imp_df = pd.DataFrame(clf.feature_importances_,X.columns,columns=['Importance'])
imp_df.sort_values(by=['Importance'],ascending=False)

                                    Importance
tsw_ta_units_30-40                1.278711e-01
tsw_ta_mnsqft_30-40               1.098372e-01
tsw_ta_units_<=30                 9.905321e-02
tsw_ta_units_40-50                6.800281e-02
tsw_ta_mnsqft_<=30                6.618013e-02
tsw_ta_mnsqft_40-50               6.256402e-02
Unsold in units                   4.767063e-02
open_stock_units                  4.485428e-02
New Launch Absorption in Units    4.429728e-02
Unsold in Mn Sqft                 4.069050e-02
open_stock_mnsqft                 2.729714e-02
tsw_ta_mnsqft_50-60               2.475165e-02
tsw_ta_units_50-60                2.471246e-02
New Launch Absorption in Mn Sqft  1.673322e-02
new_abs_mnsqft_30-40              1.130208e-02
new_abs_units_<=30                1.009932e-02
new_abs_mnsqft_<=30               8.768728e-03
tsw_ta_mnsqft_60-70               8.453842e-03
overhang                          8.444230e-03
tsw_ta_units_60-70                8.317952e-03
tsw_ta_mnsqft_>1                  7.852680e-03
new_abs_units_30-40               7.008248e-03
tsw_ta_units_>1                   6.977992e-03
tsw_un_units_30-40                4.783661e-03
tsw_ta_units_90-1                 4.095661e-03
tsw_un_units_40-50                3.678195e-03
tsw_ta_units_70-80                3.561543e-03
tsw_un_mnsqft_>1                  3.514204e-03
tsw_ta_mnsqft_70-80               3.363350e-03
tsw_un_units_>1                   3.306382e-03
...                                        ...
semi_urban                        3.139739e-06
hotel_price_4_max                 2.472593e-06
education_institute               7.793710e-07
jain                              7.502468e-07
rent_property_60k_90k             6.856945e-07
rental_per_sqft_100_abv           5.995141e-07
Under_Construction_Area           3.715749e-07
Rent_Property_90_1.5L             1.083012e-07
Forest                            0.000000e+00
tourism                           0.000000e+00
Other                             0.000000e+00
sikh                              0.000000e+00
restaurant_rs_3000_5000           0.000000e+00
airport                           0.000000e+00
atm                               0.000000e+00
Commercial_Complex                0.000000e+00
buddhist                          0.000000e+00
traffic_junctions                 0.000000e+00
special_economic_zone             0.000000e+00
mall                              0.000000e+00
hotel                             0.000000e+00
service_centers                   0.000000e+00
school                            0.000000e+00
retail_store                      0.000000e+00
recreation                        0.000000e+00
rest_blw_2.5                      0.000000e+00
pharmacy                          0.000000e+00
industry                          0.000000e+00
Airport                           0.000000e+00
park                              0.000000e+00

[253 rows x 1 columns]

In [15]:
from sklearn.ensemble import GradientBoostingRegressor

clf = GradientBoostingRegressor(learning_rate=0.1, random_state=0).fit(X_train, y_train)
print('Accuracy of GBDT classifier on training set: {:.2f}'
     .format(clf.score(X_train, y_train)))
print('Accuracy of GBDT classifier on test set: {:.2f}'
     .format(clf.score(X_test, y_test)))

Accuracy of GBDT classifier on training set: 0.99
Accuracy of GBDT classifier on test set: 0.97

In [16]:
imp_df = pd.DataFrame(clf.feature_importances_,X.columns,columns=['Importance'])
imp_df.sort_values(by=['Importance'],ascending=False).head(10)

                                Importance
tsw_ta_units_30-40                0.290189
tsw_ta_units_<=30                 0.217236
tsw_ta_units_40-50                0.131797
New Launch Absorption in Units    0.080003
Unsold in units                   0.063455
Unsold in Mn Sqft                 0.046598
tsw_ta_units_50-60                0.028371
tsw_ta_mnsqft_50-60               0.018348
tsw_ta_mnsqft_30-40               0.018147
tsw_ta_units_60-70                0.016372

# Without absorption columns

In [17]:
dset2 = dset1.copy()
dset2.columns[49:67]

Index(['tsw_ta_units_<=30', 'tsw_ta_units_30-40', 'tsw_ta_units_40-50',
       'tsw_ta_units_50-60', 'tsw_ta_units_60-70', 'tsw_ta_units_70-80',
       'tsw_ta_units_80-90', 'tsw_ta_units_90-1', 'tsw_ta_units_>1',
       'tsw_ta_mnsqft_<=30', 'tsw_ta_mnsqft_30-40', 'tsw_ta_mnsqft_40-50',
       'tsw_ta_mnsqft_50-60', 'tsw_ta_mnsqft_60-70', 'tsw_ta_mnsqft_70-80',
       'tsw_ta_mnsqft_80-90', 'tsw_ta_mnsqft_90-1', 'tsw_ta_mnsqft_>1'],
      dtype='object')

In [18]:
dset2 = dset2.drop(columns=dset2.columns[49:67])
dset2

,MicroMarket,cl_pincode,index,open_stock_units,open_stock_mnsqft,overhang,New Launch Wt Average Price (/Sqft),Wt. Average Price Absorbed unit (INR/Sft),Wt. Average Price Available unit (INR/Sft),New Launch Absorption in Units,...,christian,hindu,jain,muslim,sikh,rural,semi_urban,urban,Total Absorption in units,Total Absorption in Mn Sqft
49,Alwarpet,600018,2019Q4,0,0.00,24,15900.00,15900.000000,15900.000000,5,...,0.01,0.97,0.0,0.02,0,0,0,1,5,0.02
50,Alwarpet,600018,2020Q1,345,1.22,85,15900.00,15900.000000,15900.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,8,0.03
85,Cenotaph Road,600018,2016Q1,82,0.21,34,20000.00,20000.000000,20000.000000,5,...,0.01,0.97,0.0,0.02,0,0,0,1,8,0.02
86,Cenotaph Road,600018,2016Q2,112,0.28,49,20000.00,20000.000000,20000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,4,0.01
87,Cenotaph Road,600018,2016Q3,103,0.27,55,20000.00,20000.000000,20000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,2,0.00
88,Cenotaph Road,600018,2016Q4,97,0.24,57,20000.00,20000.000000,20000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,1,0.00
89,Cenotaph Road,600018,2017Q1,96,0.24,81,20000.00,22000.000000,21333.333333,0,...,0.01,0.97,0.0,0.02,0,0,0,1,1,0.00
90,Cenotaph Road,600018,2017Q2,93,0.24,92,20000.00,22000.000000,22000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,1,0.00
91,Cenotaph Road,600018,2017Q3,90,0.24,89,20000.00,22000.000000,22000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,1,0.00
92,Cenotaph Road,600018,2017Q4,87,0.21,87,20000.00,22000.000000,22000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,0,0.00
93,Cenotaph Road,600018,2018Q1,87,0.21,87,20000.00,22000.000000,22000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,0,0.00
94,Cenotaph Road,600018,2018Q2,87,0.21,86,20000.00,22000.000000,22000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,1,0.00
95,Cenotaph Road,600018,2018Q3,82,0.21,80,20000.00,22000.000000,22000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,2,0.00
96,Cenotaph Road,600018,2018Q4,75,0.19,72,20000.00,22000.000000,22000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,3,0.00
97,Cenotaph Road,600018,2019Q1,68,0.18,63,20000.00,22000.000000,22000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,3,0.01
98,Cenotaph Road,600018,2019Q2,57,0.15,48,20000.00,22000.000000,22000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,3,0.00
99,Cenotaph Road,600018,2019Q3,49,0.12,44,20000.00,22000.000000,22000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,2,0.00
100,Cenotaph Road,600018,2019Q4,44,0.12,39,20000.00,22000.000000,22000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,1,0.00
101,Cenotaph Road,600018,2020Q1,42,0.12,38,20000.00,22000.000000,20666.666667,0,...,0.01,0.97,0.0,0.02,0,0,0,1,0,0.00
121,Teynampet,600018,2012Q2,71,0.12,45,12000.00,12000.000000,12000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,2,0.00
122,Teynampet,600018,2012Q3,66,0.09,65,12000.00,12000.000000,12000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,1,0.00
123,Teynampet,600018,2012Q4,62,0.09,61,12000.00,12000.000000,12000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,1,0.00
124,Teynampet,600018,2013Q1,54,0.09,39,12000.00,13000.000000,13000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,4,0.00
125,Teynampet,600018,2013Q2,46,0.07,34,12000.00,13000.000000,13000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,2,0.00
126,Teynampet,600018,2013Q3,42,0.06,32,12000.00,13000.000000,13000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,0,0.00
127,Teynampet,600018,2013Q4,38,0.06,23,12000.00,13000.000000,13000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,5,0.00
128,Teynampet,600018,2014Q1,22,0.03,12,12000.00,13000.000000,13000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,4,0.00
129,Teynampet,600018,2014Q2,13,0.02,7,12000.00,13000.000000,13000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,3,0.00
130,Teynampet,600018,2014Q3,3,0.00,1,12000.00,13000.000000,13000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,2,0.00
131,Teynampet,600018,2014Q4,0,0.00,0,12000.00,13000.000000,13000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8436,Kolapakkam,600074,2012Q4,353,0.39,34,5000.00,4917.333333,4822.000000,25,...,0.03,0.92,0.0,0.05,0,0,0,1,63,0.09
8437,Kolapakkam,600074,2013Q1,307,0.33,28,5000.00,4954.000000,4832.000000,0,...,0.03,0.92,0.0,0.05,0,0,0,1,20,0.03
8438,Kolapakkam,600074,2013Q2,323,0.33,33,3800.00,4243.000000,4620.333333,5,...,0.03,0.92,0.0,0.05,0,0,0,1,17,0.01
8439,Kolapakkam,600074,2013Q3,318,0.32,33,3800.00,4591.666667,4670.000000,0,...,0.03,0.92,0.0,0.05,0,0,0,1,12,0.00
8440,Kolapakkam,600074,2013Q4,286,0.28,50,3800.00,4432.666667,4710.333333,0,...,0.03,0.92,0.0,0.05,0,0,0,1,8,0.00
8441,Kolapakkam,600074,2014Q1,262,0.26,73,4843.77,4610.000000,4721.666667,6,...,0.03,0.92,0.0,0.05,0,0,0,1,12,0.01
8442,Kolapakkam,600074,2014Q2,362,0.37,114,4440.00,4651.333333,4716.666667,24,...,0.03,0.92,0.0,0.05,0,0,0,1,39,0.03
8443,Kolapakkam,600074,2014Q3,843,0.81,94,4440.00,4519.333333,4595.000000,0,...,0.03,0.92,0.0,0.05,0,0,0,1,56,0.06
8444,Kolapakkam,600074,2014Q4,694,0.67,58,4440.00,4605.666667,4632.333333,0,...,0.03,0.92,0.0,0.05,0,0,0,1,39,0.03
8445,Kolapakkam,600074,2015Q1,592,0.57,43,4440.00,4582.000000,4661.333333,0,...,0.03,0.92,0.0,0.05,0,0,0,1,26,0.03
8446,Kolapakkam,600074,2015Q2,583,0.59,44,4800.00,4723.666667,4707.666667,10,...,0.03,0.92,0.0,0.05,0,0,0,1,40,0.04
8447,Kolapakkam,600074,2015Q3,606,0.63,52,5500.00,4871.666667,4817.666667,9,...,0.03,0.92,0.0,0.05,0,0,0,1,42,0.05
8448,Kolapakkam,600074,2015Q4,687,0.85,55,5500.00,5202.333333,4994.000000,0,...,0.03,0.92,0.0,0.05,0,0,0,1,33,0.05
8449,Kolapakkam,600074,2016Q1,1434,1.74,110,5074.75,5082.666667,5043.000000,43,...,0.03,0.92,0.0,0.05,0,0,0,1,101,0.13
8450,Kolapakkam,600074,2016Q2,1659,1.97,80,5074.75,5221.666667,5007.000000,0,...,0.03,0.92,0.0,0.05,0,0,0,1,71,0.10
8451,Kolapakkam,600074,2016Q3,1431,1.69,60,5074.75,5034.666667,5021.000000,0,...,0.03,0.92,0.0,0.05,0,0,0,1,80,0.09
8452,Kolapakkam,600074,2016Q4,1216,1.44,49,5074.75,4964.333333,5029.333333,0,...,0.03,0.92,0.0,0.05,0,0,0,1,42,0.05
8453,Kolapakkam,600074,2017Q1,1110,1.32,53,5074.75,4837.000000,5056.333333,0,...,0.03,0.92,0.0,0.05,0,0,0,1,33,0.03
8454,Kolapakkam,600074,2017Q2,1013,1.22,57,5074.75,4696.333333,5126.333333,0,...,0.03,0.92,0.0,0.05,0,0,0,1,37,0.04
8455,Kolapakkam,600074,2017Q3,949,1.19,74,6440.00,5251.333333,5311.333333,4,...,0.03,0.92,0.0,0.05,0,0,0,1,31,0.04
8456,Kolapakkam,600074,2017Q4,923,1.22,78,6440.00,5085.333333,5401.666667,0,...,0.03,0.92,0.0,0.05,0,0,0,1,41,0.05
8457,Kolapakkam,600074,2018Q1,918,1.20,70,5628.00,5260.000000,5381.666667,6,...,0.03,0.92,0.0,0.05,0,0,0,1,76,0.09
8458,Kolapakkam,600074,2018Q2,999,1.27,64,4600.00,4920.666667,5293.000000,5,...,0.03,0.92,0.0,0.05,0,0,0,1,48,0.05
8459,Kolapakkam,600074,2018Q3,1064,1.35,59,5000.00,4865.333333,5252.333333,2,...,0.03,0.92,0.0,0.05,0,0,0,1,59,0.06
8460,Kolapakkam,600074,2018Q4,1018,1.33,48,6440.00,5085.666667,5419.333333,1,...,0.03,0.92,0.0,0.05,0,0,0,1,69,0.08
8461,Kolapakkam,600074,2019Q1,855,1.15,40,6440.00,4978.000000,5492.666667,0,...,0.03,0.92,0.0,0.05,0,0,0,1,57,0.06
8462,Kolapakkam,600074,2019Q2,711,0.99,36,6440.00,4812.333333,5577.666667,0,...,0.03,0.92,0.0,0.05,0,0,0,1,31,0.03
8463,Kolapakkam,600074,2019Q3,631,0.90,37,6440.00,4882.333333,5639.666667,0,...,0.03,0.92,0.0,0.05,0,0,0,1,22,0.03
8464,Kolapakkam,600074,2019Q4,560,0.82,45,6440.00,4798.000000,5733.333333,0,...,0.03,0.92,0.0,0.05,0,0,0,1,23,0.03
8465,Kolapakkam,600074,2020Q1,486,0.74,51,6440.00,5319.333333,5799.666667,0,...,0.03,0.92,0.0,0.05,0,0,0,1,20,0.02

In [508]:
X = dset2.iloc[:,3:-2]
y = dset2.iloc[:,-2]

In [510]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 0)

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

linreg = LinearRegression().fit(X_train_scaled, y_train)

print('linear model coeff (w): {}'
     .format(linreg.coef_))
print('linear model intercept (b): {:.3f}'
     .format(linreg.intercept_))
print('R-squared score (training): {:.3f}'
     .format(linreg.score(X_train_scaled, y_train)))
print('R-squared score (test): {:.3f}'
     .format(linreg.score(X_test_scaled, y_test)))

linear model coeff (w): [ 8.19000000e+03  1.31876732e-10  0.00000000e+00 -2.76259016e-11
  4.54747351e-12  1.18234311e-11  1.23691279e-10 -8.73114914e-11
 -8.48700000e+03 -1.75077730e-10  1.87800000e+03  1.45000000e+03
  8.25000000e+02  4.90000000e+02  3.80000000e+02  3.46000000e+02
  1.14000000e+03  1.96000000e+02  4.57000000e+02 -7.16227078e-12
  4.38831194e-11 -2.16004992e-11  5.22959454e-12  2.61479727e-11
  4.66116035e-12  8.23519031e-12  1.82751592e-11  2.84217094e-13
 -1.59161573e-11  2.26236807e-11 -3.20596882e-11 -3.58113539e-12
 -9.90496574e-12  1.52340363e-11  4.28208580e-11  2.50111043e-11
 -6.33804120e-12  9.60653779e-12 -1.83035809e-11  3.87103682e-11
  3.46744855e-12  1.17310606e-11 -1.33582034e-11 -4.18403090e-11
 -2.75690581e-11  7.53175300e-12 -2.31921149e-11 -1.20508048e-11
 -1.31876732e-11 -5.51381163e-12 -6.11066753e-12 -5.59907676e-12
 -2.46132004e-11 -8.24229573e-13 -1.39266376e-11  2.45563569e-11
  1.50635060e-11  1.25055521e-11  7.27595761e-12  1.34150469e-11
  8.10018719e-12  3.61382035e-11  5.49960077e-12  1.84172677e-11
  4.54747351e-13  4.95674612e-11  5.10453901e-11 -7.70228326e-12
 -7.73070497e-12  1.96962446e-11  1.98951966e-13 -1.02602371e-11
 -2.34479103e-11  2.55795385e-12  1.20721211e-11  3.56124019e-11
  3.05533376e-11 -3.91651156e-11 -4.01456646e-11 -2.65032440e-11
 -2.51390020e-11 -4.62279104e-11 -2.63469246e-11  1.60582658e-11
 -4.53610483e-11  1.41255896e-11 -1.28466127e-11  1.95399252e-11
  1.71951342e-11  1.76214598e-12 -2.25099939e-11 -3.53281848e-11
 -1.45519152e-11 -4.12541112e-11  1.96678229e-11 -1.27329258e-11
 -1.92983407e-11  3.77724518e-11  1.38840051e-11  9.80548975e-12
  1.83320026e-12  1.71667125e-11 -1.31237243e-11  4.17799129e-12
  2.13162821e-12 -1.92983407e-11 -2.03215222e-11 -1.47792889e-11
  2.92743607e-12  2.85353963e-11  2.05773176e-11  8.92441676e-12
  4.21778168e-11  9.12336873e-12 -1.82751592e-11  3.79429821e-12
  2.19699814e-11  2.53095322e-11 -2.17426077e-12 -1.19371180e-11
 -2.23465690e-11 -6.15330009e-12  5.65592018e-12 -2.15152340e-11
  9.74864633e-12 -1.91846539e-11 -5.11590770e-13  6.79278855e-12
 -1.55182533e-11  2.96438429e-11  2.62616595e-11  2.50111043e-12
  1.70530257e-12  2.83222334e-11 -1.39266376e-11 -4.55315785e-11
  1.57740487e-12 -1.55182533e-11  1.15036869e-11 -8.46966941e-12
 -6.53699317e-13  1.13686838e-12  2.17710294e-11 -9.70601377e-12
  4.48636683e-11 -3.59108299e-11 -2.39310793e-11  7.00595137e-12
  6.33804120e-12  1.56887836e-11  2.90754087e-11  2.46700438e-11
  0.00000000e+00 -4.77484718e-12 -3.09796633e-12  2.34763320e-11
  7.50333129e-12  5.00222086e-12 -2.61479727e-12  0.00000000e+00
 -5.82645043e-12  0.00000000e+00  2.21689334e-12  0.00000000e+00
  0.00000000e+00 -1.28466127e-11  0.00000000e+00 -8.37019343e-12
 -1.13686838e-12 -5.54223334e-12  3.75166564e-12 -7.84439180e-12
 -4.88853402e-12  3.75166564e-12 -3.86535248e-12  4.03588274e-12
  1.25623956e-11 -1.22781785e-11 -8.29913915e-12 -4.09272616e-12
 -1.02318154e-12  1.06297193e-11 -3.18323146e-12  1.12549969e-11
 -5.34328137e-12  2.71711542e-11  3.06954462e-12  4.54747351e-13
  2.50111043e-12 -5.40012479e-13  6.76436684e-12  2.01225703e-11
 -4.27746727e-12 -2.65742983e-12 -4.12114787e-12  3.43334250e-11
 -3.50723894e-11 -1.08002496e-11 -3.48165941e-12  8.12860890e-12
 -1.79625204e-11 -5.19548848e-11 -5.40012479e-12  0.00000000e+00
  0.00000000e+00  1.36424205e-12  3.52429197e-12  1.31876732e-11
 -2.33058017e-12  0.00000000e+00  0.00000000e+00  0.00000000e+00
 -9.09494702e-13 -2.23110419e-12 -4.90985030e-12  0.00000000e+00
  0.00000000e+00  1.36424205e-12  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00 -1.70530257e-12  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00 -4.54747351e-13
 -1.36424205e-12  9.94759830e-13  2.27373675e-12  0.00000000e+00
  5.79802872e-12  1.47792889e-12  8.18545232e-12]
linear model intercept (b): -0.000
R-squared score (training): 1.000
R-squared score (test): 1.000

In [21]:
coeff_df = pd.DataFrame(linreg.coef_,X.columns,columns=['Coefficient'])
coeff_df.sort_values(by=['Coefficient'],ascending=False).head(10)

                     Coefficient
open_stock_units          8190.0
tsw_new_units_<=30        1878.0
tsw_new_units_30-40       1450.0
tsw_new_units_80-90       1140.0
tsw_new_units_40-50        825.0
tsw_new_units_50-60        490.0
tsw_new_units_>1           457.0
tsw_new_units_60-70        380.0
tsw_new_units_70-80        346.0
tsw_new_units_90-1         196.0

In [22]:
linridge = Ridge(alpha=0.0).fit(X_train_scaled, y_train)

print('ridge regression linear model intercept: {}'
     .format(linridge.intercept_))
print('ridge regression linear model coeff:\n{}'
     .format(linridge.coef_))
print('R-squared score (training): {:.3f}'
     .format(linridge.score(X_train_scaled, y_train)))
print('R-squared score (test): {:.3f}'
     .format(linridge.score(X_test_scaled, y_test)))
print('Number of non-zero features: {}'
     .format(np.sum(linridge.coef_ != 0)))

ridge regression linear model intercept: 183.24472983898548
ridge regression linear model coeff:
[ 8.19000000e+03  1.54159352e-10  7.35411732e-13 -2.73558953e-11
  6.07514039e-12  1.43209888e-11  1.33013600e-10 -9.41327016e-11
 -8.48700000e+03 -1.82581061e-10  1.87800000e+03  1.45000000e+03
  8.25000000e+02  4.90000000e+02  3.80000000e+02  3.46000000e+02
  1.14000000e+03  1.96000000e+02  4.57000000e+02 -2.72848411e-12
  4.54178917e-11 -1.73940862e-11  7.38964445e-12  2.43396414e-11
  7.92965693e-12  1.72803993e-11  1.73372428e-11  2.27373675e-12
 -1.50066626e-11  2.52384780e-11 -2.93312041e-11 -1.13686838e-12
 -1.41540113e-11  1.47792889e-11  6.23003871e-11  2.19415597e-11
 -6.16751095e-12  8.64019967e-12 -1.94404493e-11  3.73177045e-11
  1.93267624e-12  1.59445790e-11 -1.30171429e-11 -6.57109922e-11
 -2.38742359e-11  5.94013727e-12 -2.50111043e-11 -1.03455022e-11
 -1.32445166e-11 -4.88853402e-12 -7.67386155e-12 -4.00746103e-12
 -2.02362571e-11 -1.59161573e-12 -1.15107923e-11  2.70574674e-11
  1.54614099e-11  1.18802745e-11  6.56541488e-12  1.47224455e-11
  5.74118530e-12  3.04680725e-11  6.65068001e-12  1.90993887e-11
  6.20431131e+00  2.26364300e+01  8.80702593e+01  1.86416071e+02
  5.88744311e+01  2.95804048e+02  4.08674776e+01 -3.18439025e+01
  1.83781660e+02  4.63104194e+02 -2.63138724e+01  3.13999195e+02
  1.17971944e+02 -1.45915936e+02 -1.00342707e+02 -1.04046666e+02
 -2.76225307e+02 -2.61554386e+02 -2.03666596e+02 -8.95502666e+00
 -1.00034558e+02  2.52005753e+02  2.98543562e+02  5.90586814e+01
  5.14353491e+01 -2.86318448e+01 -3.87437462e+02  3.39059445e+02
  6.86958045e+02  1.63340248e+02 -1.70219453e+02 -3.88233210e+02
 -1.38423960e+02 -2.09884226e+02  3.57966256e+02  1.41700606e+02
 -3.54508979e+02 -6.84869490e+01 -1.20201788e+02 -1.27483428e+02
 -3.85883074e+01  6.92444604e+02 -4.60108530e+02  8.32023430e+01
 -1.78445466e+02  5.20269698e+02  1.37358784e+01  6.81905239e+01
 -1.79519909e+02 -2.41190439e+02  1.81068551e+02  1.28958205e+02
 -1.06761644e+02 -2.65369041e+02  1.32890622e+02  1.38198761e+02
  3.07629206e+00 -4.53320920e+02 -5.15535645e+02  6.26455874e+02
  1.59606083e+01 -3.17064655e+02  1.52040986e+02  5.74790622e+01
 -1.82660974e+02  9.42336938e+01 -2.69438090e+01 -1.59082519e+02
  7.18961365e+01 -4.63623361e+02 -4.14259519e+02 -6.15976949e+02
  1.45280527e+02  1.03411613e+02  4.43726343e+02 -6.44450828e+01
  8.10852421e+01 -1.54666030e+01 -5.71447087e+01 -4.28743931e+02
  1.00696350e+02 -5.60593034e+01  5.56789668e+02 -4.28209756e+02
 -1.69539951e+02  4.96513955e+02 -2.23147512e+02  2.58445651e+02
 -1.00539998e+02  8.44261139e+01  3.07674228e+01 -5.26004348e+01
 -5.85941178e+01  7.65600750e+00 -3.92190063e+00  2.41983192e+02
 -3.85286988e+01 -7.66210210e+01 -4.14272083e+01  1.98640924e+02
  1.03563364e+02  5.78928838e+01 -1.01561954e+01  1.87188547e+01
  2.55736595e+01  8.87103156e+01  8.69034612e+00 -7.35990320e+00
  1.94419745e+01 -8.92256329e+00  7.20837531e-01  9.11750590e+00
 -4.00974595e+01  6.72999044e+01  1.26696739e+02 -6.76133383e+01
  1.65479607e+01 -1.61725374e+02  3.34562938e+01  7.02100402e+00
 -1.03875268e+01  1.27149791e+02  2.29093096e+01 -2.23873817e+01
 -5.12512492e+01 -6.55979442e+01 -9.14663321e+01  6.95362604e+01
  1.31463609e+02  4.34609771e+01  2.14658319e+01  5.54586304e+01
 -1.29908142e+01 -1.39312178e+02 -1.04597445e+02  1.38718575e+02
  1.91716182e+01 -1.55862524e+02 -2.08530782e+02  4.40238650e+00
  7.62907257e+01  3.17877983e-01  6.43528834e+01 -4.88714002e+01
  2.09892832e+01  5.65510699e+01  1.33469930e+02  3.63274603e+01
 -1.57037424e+00 -9.13396623e+00 -4.04955994e+01  3.22698018e+01
 -2.30867444e+00  2.67736054e+00  9.98537972e+00 -7.45404208e+00
 -9.23461472e+01 -2.06358076e+01  6.28596349e+00  3.85273030e+01
 -4.28548685e+01  1.28280843e+01  3.04707162e+00 -1.27600651e+01
  3.97872309e+00 -7.64892920e+01  5.97251896e+00  2.28749266e+01
 -1.81840107e+02 -1.73821293e+02 -1.90443385e+02]
R-squared score (training): 1.000
R-squared score (test): 1.000
Number of non-zero features: 235

In [23]:


coeff_df = pd.DataFrame(linridge.coef_,X.columns,columns=['Coefficient'])
coeff_df.sort_values(by=['Coefficient'],ascending=False).head(10)

                     Coefficient
open_stock_units     8190.000000
tsw_new_units_<=30   1878.000000
tsw_new_units_30-40  1450.000000
tsw_new_units_80-90  1140.000000
tsw_new_units_40-50   825.000000
TOT_M                 692.444604
ava_radio             686.958045
MAINWORK_F            626.455874
MARGWORK_0_3_P        556.789668
F_06                  520.269698

In [24]:
linlasso = Lasso(alpha=0.1, max_iter = 10000).fit(X_train_scaled, y_train)
print('lasso regression linear model intercept: {}'
     .format(linlasso.intercept_))
print('lasso regression linear model coeff:\n{}'
     .format(linlasso.coef_))
print('Non-zero features: {}'
     .format(np.sum(linlasso.coef_ != 0)))
print('R-squared score (training): {:.3f}'
     .format(linlasso.score(X_train_scaled, y_train)))
print('R-squared score (test): {:.3f}\n'
     .format(linlasso.score(X_test_scaled, y_test)))
print('Features with non-zero weight (sorted by absolute magnitude):')

for e in sorted (list(zip(list(X), linlasso.coef_)),
                key = lambda e: -abs(e[1])):
    if e[1] != 0:
        print('\t{}, {:.3f}'.format(e[0], e[1]))

lasso regression linear model intercept: 60.08811713132171
lasso regression linear model coeff:
[ 1.63469241e+02  1.08388150e+02 -1.74054999e+02 -0.00000000e+00
 -0.00000000e+00 -1.27528321e+01  0.00000000e+00  4.91016831e+02
  0.00000000e+00  0.00000000e+00  1.70556163e+01  0.00000000e+00
  4.86769222e+01  0.00000000e+00  1.12403628e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  3.80366949e+02  2.35960447e+02  5.72980965e+01  1.03668194e+02
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  2.49945083e+01  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00 -0.00000000e+00  0.00000000e+00
 -0.00000000e+00  0.00000000e+00 -0.00000000e+00 -0.00000000e+00
 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00  0.00000000e+00
  0.00000000e+00 -0.00000000e+00  0.00000000e+00 -0.00000000e+00
 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00
  3.03867527e-01  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  6.25164093e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00 -0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00 -0.00000000e+00  0.00000000e+00 -0.00000000e+00
 -0.00000000e+00  0.00000000e+00 -0.00000000e+00  0.00000000e+00
 -0.00000000e+00  0.00000000e+00 -0.00000000e+00  0.00000000e+00
  0.00000000e+00 -1.00385348e+01 -0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  3.40047614e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00
 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00
 -0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00 -0.00000000e+00
 -0.00000000e+00 -0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00 -0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00 -0.00000000e+00
 -1.01485891e+00 -0.00000000e+00  0.00000000e+00  0.00000000e+00
 -0.00000000e+00  0.00000000e+00 -0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
 -0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
 -0.00000000e+00  0.00000000e+00  0.00000000e+00 -0.00000000e+00
 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00
  0.00000000e+00  0.00000000e+00 -0.00000000e+00  0.00000000e+00
 -2.95368288e-01  0.00000000e+00  0.00000000e+00 -0.00000000e+00
  0.00000000e+00  0.00000000e+00 -0.00000000e+00 -0.00000000e+00
 -0.00000000e+00  0.00000000e+00  0.00000000e+00 -0.00000000e+00
 -0.00000000e+00 -0.00000000e+00  0.00000000e+00 -0.00000000e+00
 -0.00000000e+00 -0.00000000e+00 -0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00 -0.00000000e+00 -0.00000000e+00
 -1.57163793e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  9.48843592e-01 -0.00000000e+00  0.00000000e+00
  0.00000000e+00 -2.28511208e-01  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  3.67018046e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00 -0.00000000e+00
  5.85826354e-01  0.00000000e+00  6.35244060e-02  0.00000000e+00
  1.15017826e+00 -0.00000000e+00 -0.00000000e+00]
Non-zero features: 26
R-squared score (training): 0.809
R-squared score (test): 0.715

Features with non-zero weight (sorted by absolute magnitude):
	New Launch Absorption in Mn Sqft, 491.017
	new_abs_units_<=30, 380.367
	new_abs_units_30-40, 235.960
	overhang, -174.055
	open_stock_units, 163.469
	open_stock_mnsqft, 108.388
	new_abs_units_50-60, 103.668
	new_abs_units_40-50, 57.298
	tsw_new_units_40-50, 48.677
	new_abs_units_>1, 24.995
	tsw_new_units_<=30, 17.056
	Wt. Average Price Available unit (INR/Sft), -12.753
	as_fourwheeler, -10.039
	rf_bt_brick, 6.252
	service_providers, 3.670
	P_SC, 3.400
	hospital, -1.572
	rural, 1.150
	tsw_new_units_60-70, 1.124
	restaurant_rs_0_500, -1.015
	msme, 0.949
	hindu, 0.586
	age, 0.304
	Sale_Property_50_80L, -0.295
	post_office, -0.229
	muslim, 0.064

In [ ]:
print('Lasso regression: effect of alpha regularization\n\
parameter on number of features kept in final model\n')

for alpha in [0.1, 0.5, 1, 2, 3, 5, 10, 20, 50]:
    linlasso = Lasso(alpha, max_iter = 10000).fit(X_train_scaled, y_train)
    r2_train = linlasso.score(X_train_scaled, y_train)
    r2_test = linlasso.score(X_test_scaled, y_test)
    
    print('Alpha = {:.2f}\nFeatures kept: {}, r-squared training: {:.2f}, \
r-squared test: {:.2f}\n'
         .format(alpha, np.sum(linlasso.coef_ != 0), r2_train, r2_test))

In [25]:
coeff_df = pd.DataFrame(linlasso.coef_,X.columns,columns=['Coefficient'])
coeff_df.sort_values(by=['Coefficient'],ascending=False).head(10)

                                  Coefficient
New Launch Absorption in Mn Sqft   491.016831
new_abs_units_<=30                 380.366949
new_abs_units_30-40                235.960447
open_stock_units                   163.469241
open_stock_mnsqft                  108.388150
new_abs_units_50-60                103.668194
new_abs_units_40-50                 57.298097
tsw_new_units_40-50                 48.676922
new_abs_units_>1                    24.994508
tsw_new_units_<=30                  17.055616

In [513]:
clf = RandomForestRegressor(max_features=210,random_state=0).fit(X_train, y_train)
print('Accuracy of RF regressor on training set: {:.2f}'
     .format(clf.score(X_train, y_train)))
print('Accuracy of RF regressor on test set: {:.2f}'
     .format(clf.score(X_test, y_test)))

Accuracy of RF regressor on training set: 0.97
Accuracy of RF regressor on test set: 0.84

In [514]:
imp_df = pd.DataFrame(clf.feature_importances_,X.columns,columns=['Importance'])
imp_df.sort_values(by=['Importance'],ascending=False).head(10)

                                  Importance
Unsold in units                     0.310893
New Launch Absorption in Units      0.224926
overhang                            0.100917
open_stock_units                    0.090889
Unsold in Mn Sqft                   0.066080
New Launch Absorption in Mn Sqft    0.044270
open_stock_mnsqft                   0.016089
new_abs_mnsqft_30-40                0.013415
new_abs_units_30-40                 0.009128
new_abs_units_<=30                  0.006371

In [511]:
clf = GradientBoostingRegressor(learning_rate=0.1, random_state=0).fit(X_train, y_train)
print('Accuracy of GBDT regressor on training set: {:.2f}'
     .format(clf.score(X_train, y_train)))
print('Accuracy of GBDT regressor on test set: {:.2f}'
     .format(clf.score(X_test, y_test)))

Accuracy of GBDT regressor on training set: 0.94
Accuracy of GBDT regressor on test set: 0.83

In [512]:
imp_df = pd.DataFrame(clf.feature_importances_,X.columns,columns=['Importance'])
imp_df.sort_values(by=['Importance'],ascending=False).head(10)

                                  Importance
New Launch Absorption in Units      0.324902
Unsold in units                     0.185756
open_stock_units                    0.138409
overhang                            0.106998
Unsold in Mn Sqft                   0.105722
New Launch Absorption in Mn Sqft    0.045483
open_stock_mnsqft                   0.020242
new_abs_mnsqft_<=30                 0.011110
new_abs_units_30-40                 0.007735
tsw_un_mnsqft_>1                    0.006996

In [6]:
dset3 = pd.read_excel('final4.xlsx',parse_dates=['index'])
dset3

,MicroMarket,cl_pincode,index,open_stock_units,open_stock_mnsqft,overhang,New Launch Wt Average Price (/Sqft),Wt. Average Price Absorbed unit (INR/Sft),Wt. Average Price Available unit (INR/Sft),New Launch Absorption in Units,...,christian,hindu,jain,muslim,sikh,rural,semi_urban,urban,Total Absorption in units,Total Absorption in Mn Sqft
0,Alwarpet,600018,2007-07-01,0,0.00,0,NaN,NaN,NaN,0,...,0.01,0.97,0.0,0.02,0,0,0,1,0,0.00
1,Alwarpet,600018,2007-10-01,0,0.00,0,NaN,NaN,NaN,0,...,0.01,0.97,0.0,0.02,0,0,0,1,0,0.00
2,Alwarpet,600018,2008-01-01,0,0.00,0,NaN,NaN,NaN,0,...,0.01,0.97,0.0,0.02,0,0,0,1,0,0.00
3,Alwarpet,600018,2008-04-01,0,0.00,0,NaN,NaN,NaN,0,...,0.01,0.97,0.0,0.02,0,0,0,1,0,0.00
4,Alwarpet,600018,2008-07-01,0,0.00,0,NaN,NaN,NaN,0,...,0.01,0.97,0.0,0.02,0,0,0,1,0,0.00
5,Alwarpet,600018,2008-10-01,0,0.00,0,NaN,NaN,NaN,0,...,0.01,0.97,0.0,0.02,0,0,0,1,0,0.00
6,Alwarpet,600018,2009-01-01,0,0.00,0,NaN,NaN,NaN,0,...,0.01,0.97,0.0,0.02,0,0,0,1,0,0.00
7,Alwarpet,600018,2009-04-01,0,0.00,0,NaN,NaN,NaN,0,...,0.01,0.97,0.0,0.02,0,0,0,1,0,0.00
8,Alwarpet,600018,2009-07-01,0,0.00,0,NaN,NaN,NaN,0,...,0.01,0.97,0.0,0.02,0,0,0,1,0,0.00
9,Alwarpet,600018,2009-10-01,0,0.00,0,NaN,NaN,NaN,0,...,0.01,0.97,0.0,0.02,0,0,0,1,0,0.00
10,Alwarpet,600018,2010-01-01,0,0.00,0,NaN,NaN,NaN,0,...,0.01,0.97,0.0,0.02,0,0,0,1,0,0.00
11,Alwarpet,600018,2010-04-01,0,0.00,0,NaN,NaN,NaN,0,...,0.01,0.97,0.0,0.02,0,0,0,1,0,0.00
12,Alwarpet,600018,2010-07-01,0,0.00,0,NaN,NaN,NaN,0,...,0.01,0.97,0.0,0.02,0,0,0,1,0,0.00
13,Alwarpet,600018,2010-10-01,0,0.00,0,NaN,NaN,NaN,0,...,0.01,0.97,0.0,0.02,0,0,0,1,0,0.00
14,Alwarpet,600018,2011-01-01,0,0.00,0,NaN,NaN,NaN,0,...,0.01,0.97,0.0,0.02,0,0,0,1,0,0.00
15,Alwarpet,600018,2011-04-01,0,0.00,0,NaN,NaN,NaN,0,...,0.01,0.97,0.0,0.02,0,0,0,1,0,0.00
16,Alwarpet,600018,2011-07-01,0,0.00,0,NaN,NaN,NaN,0,...,0.01,0.97,0.0,0.02,0,0,0,1,0,0.00
17,Alwarpet,600018,2011-10-01,0,0.00,0,NaN,NaN,NaN,0,...,0.01,0.97,0.0,0.02,0,0,0,1,0,0.00
18,Alwarpet,600018,2012-01-01,0,0.00,0,NaN,NaN,NaN,0,...,0.01,0.97,0.0,0.02,0,0,0,1,0,0.00
19,Alwarpet,600018,2012-04-01,0,0.00,0,NaN,NaN,NaN,0,...,0.01,0.97,0.0,0.02,0,0,0,1,0,0.00
20,Alwarpet,600018,2012-07-01,0,0.00,0,NaN,NaN,NaN,0,...,0.01,0.97,0.0,0.02,0,0,0,1,0,0.00
21,Alwarpet,600018,2012-10-01,0,0.00,0,NaN,NaN,NaN,0,...,0.01,0.97,0.0,0.02,0,0,0,1,0,0.00
22,Alwarpet,600018,2013-01-01,0,0.00,0,NaN,NaN,NaN,0,...,0.01,0.97,0.0,0.02,0,0,0,1,0,0.00
23,Alwarpet,600018,2013-04-01,0,0.00,0,NaN,NaN,NaN,0,...,0.01,0.97,0.0,0.02,0,0,0,1,0,0.00
24,Alwarpet,600018,2013-07-01,0,0.00,0,NaN,NaN,NaN,0,...,0.01,0.97,0.0,0.02,0,0,0,1,0,0.00
25,Alwarpet,600018,2013-10-01,0,0.00,0,NaN,NaN,NaN,0,...,0.01,0.97,0.0,0.02,0,0,0,1,0,0.00
26,Alwarpet,600018,2014-01-01,0,0.00,0,NaN,NaN,NaN,0,...,0.01,0.97,0.0,0.02,0,0,0,1,0,0.00
27,Alwarpet,600018,2014-04-01,0,0.00,0,NaN,NaN,NaN,0,...,0.01,0.97,0.0,0.02,0,0,0,1,0,0.00
28,Alwarpet,600018,2014-07-01,0,0.00,0,NaN,NaN,NaN,0,...,0.01,0.97,0.0,0.02,0,0,0,1,0,0.00
29,Alwarpet,600018,2014-10-01,0,0.00,0,NaN,NaN,NaN,0,...,0.01,0.97,0.0,0.02,0,0,0,1,0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8436,Kolapakkam,600074,2012-10-01,353,0.39,34,5000.00,4917.333333,4822.000000,25,...,0.03,0.92,0.0,0.05,0,0,0,1,63,0.09
8437,Kolapakkam,600074,2013-01-01,307,0.33,28,5000.00,4954.000000,4832.000000,0,...,0.03,0.92,0.0,0.05,0,0,0,1,20,0.03
8438,Kolapakkam,600074,2013-04-01,323,0.33,33,3800.00,4243.000000,4620.333333,5,...,0.03,0.92,0.0,0.05,0,0,0,1,17,0.01
8439,Kolapakkam,600074,2013-07-01,318,0.32,33,3800.00,4591.666667,4670.000000,0,...,0.03,0.92,0.0,0.05,0,0,0,1,12,0.00
8440,Kolapakkam,600074,2013-10-01,286,0.28,50,3800.00,4432.666667,4710.333333,0,...,0.03,0.92,0.0,0.05,0,0,0,1,8,0.00
8441,Kolapakkam,600074,2014-01-01,262,0.26,73,4843.77,4610.000000,4721.666667,6,...,0.03,0.92,0.0,0.05,0,0,0,1,12,0.01
8442,Kolapakkam,600074,2014-04-01,362,0.37,114,4440.00,4651.333333,4716.666667,24,...,0.03,0.92,0.0,0.05,0,0,0,1,39,0.03
8443,Kolapakkam,600074,2014-07-01,843,0.81,94,4440.00,4519.333333,4595.000000,0,...,0.03,0.92,0.0,0.05,0,0,0,1,56,0.06
8444,Kolapakkam,600074,2014-10-01,694,0.67,58,4440.00,4605.666667,4632.333333,0,...,0.03,0.92,0.0,0.05,0,0,0,1,39,0.03
8445,Kolapakkam,600074,2015-01-01,592,0.57,43,4440.00,4582.000000,4661.333333,0,...,0.03,0.92,0.0,0.05,0,0,0,1,26,0.03
8446,Kolapakkam,600074,2015-04-01,583,0.59,44,4800.00,4723.666667,4707.666667,10,...,0.03,0.92,0.0,0.05,0,0,0,1,40,0.04
8447,Kolapakkam,600074,2015-07-01,606,0.63,52,5500.00,4871.666667,4817.666667,9,...,0.03,0.92,0.0,0.05,0,0,0,1,42,0.05
8448,Kolapakkam,600074,2015-10-01,687,0.85,55,5500.00,5202.333333,4994.000000,0,...,0.03,0.92,0.0,0.05,0,0,0,1,33,0.05
8449,Kolapakkam,600074,2016-01-01,1434,1.74,110,5074.75,5082.666667,5043.000000,43,...,0.03,0.92,0.0,0.05,0,0,0,1,101,0.13
8450,Kolapakkam,600074,2016-04-01,1659,1.97,80,5074.75,5221.666667,5007.000000,0,...,0.03,0.92,0.0,0.05,0,0,0,1,71,0.10
8451,Kolapakkam,600074,2016-07-01,1431,1.69,60,5074.75,5034.666667,5021.000000,0,...,0.03,0.92,0.0,0.05,0,0,0,1,80,0.09
8452,Kolapakkam,600074,2016-10-01,1216,1.44,49,5074.75,4964.333333,5029.333333,0,...,0.03,0.92,0.0,0.05,0,0,0,1,42,0.05
8453,Kolapakkam,600074,2017-01-01,1110,1.32,53,5074.75,4837.000000,5056.333333,0,...,0.03,0.92,0.0,0.05,0,0,0,1,33,0.03
8454,Kolapakkam,600074,2017-04-01,1013,1.22,57,5074.75,4696.333333,5126.333333,0,...,0.03,0.92,0.0,0.05,0,0,0,1,37,0.04
8455,Kolapakkam,600074,2017-07-01,949,1.19,74,6440.00,5251.333333,5311.333333,4,...,0.03,0.92,0.0,0.05,0,0,0,1,31,0.04
8456,Kolapakkam,600074,2017-10-01,923,1.22,78,6440.00,5085.333333,5401.666667,0,...,0.03,0.92,0.0,0.05,0,0,0,1,41,0.05
8457,Kolapakkam,600074,2018-01-01,918,1.20,70,5628.00,5260.000000,5381.666667,6,...,0.03,0.92,0.0,0.05,0,0,0,1,76,0.09
8458,Kolapakkam,600074,2018-04-01,999,1.27,64,4600.00,4920.666667,5293.000000,5,...,0.03,0.92,0.0,0.05,0,0,0,1,48,0.05
8459,Kolapakkam,600074,2018-07-01,1064,1.35,59,5000.00,4865.333333,5252.333333,2,...,0.03,0.92,0.0,0.05,0,0,0,1,59,0.06
8460,Kolapakkam,600074,2018-10-01,1018,1.33,48,6440.00,5085.666667,5419.333333,1,...,0.03,0.92,0.0,0.05,0,0,0,1,69,0.08
8461,Kolapakkam,600074,2019-01-01,855,1.15,40,6440.00,4978.000000,5492.666667,0,...,0.03,0.92,0.0,0.05,0,0,0,1,57,0.06
8462,Kolapakkam,600074,2019-04-01,711,0.99,36,6440.00,4812.333333,5577.666667,0,...,0.03,0.92,0.0,0.05,0,0,0,1,31,0.03
8463,Kolapakkam,600074,2019-07-01,631,0.90,37,6440.00,4882.333333,5639.666667,0,...,0.03,0.92,0.0,0.05,0,0,0,1,22,0.03
8464,Kolapakkam,600074,2019-10-01,560,0.82,45,6440.00,4798.000000,5733.333333,0,...,0.03,0.92,0.0,0.05,0,0,0,1,23,0.03
8465,Kolapakkam,600074,2020-01-01,486,0.74,51,6440.00,5319.333333,5799.666667,0,...,0.03,0.92,0.0,0.05,0,0,0,1,20,0.02

In [7]:
dset3 = dset3.dropna(axis=0)
dset3

,MicroMarket,cl_pincode,index,open_stock_units,open_stock_mnsqft,overhang,New Launch Wt Average Price (/Sqft),Wt. Average Price Absorbed unit (INR/Sft),Wt. Average Price Available unit (INR/Sft),New Launch Absorption in Units,...,christian,hindu,jain,muslim,sikh,rural,semi_urban,urban,Total Absorption in units,Total Absorption in Mn Sqft
49,Alwarpet,600018,2019-10-01,0,0.00,24,15900.00,15900.000000,15900.000000,5,...,0.01,0.97,0.0,0.02,0,0,0,1,5,0.02
50,Alwarpet,600018,2020-01-01,345,1.22,85,15900.00,15900.000000,15900.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,8,0.03
85,Cenotaph Road,600018,2016-01-01,82,0.21,34,20000.00,20000.000000,20000.000000,5,...,0.01,0.97,0.0,0.02,0,0,0,1,8,0.02
86,Cenotaph Road,600018,2016-04-01,112,0.28,49,20000.00,20000.000000,20000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,4,0.01
87,Cenotaph Road,600018,2016-07-01,103,0.27,55,20000.00,20000.000000,20000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,2,0.00
88,Cenotaph Road,600018,2016-10-01,97,0.24,57,20000.00,20000.000000,20000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,1,0.00
89,Cenotaph Road,600018,2017-01-01,96,0.24,81,20000.00,22000.000000,21333.333333,0,...,0.01,0.97,0.0,0.02,0,0,0,1,1,0.00
90,Cenotaph Road,600018,2017-04-01,93,0.24,92,20000.00,22000.000000,22000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,1,0.00
91,Cenotaph Road,600018,2017-07-01,90,0.24,89,20000.00,22000.000000,22000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,1,0.00
92,Cenotaph Road,600018,2017-10-01,87,0.21,87,20000.00,22000.000000,22000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,0,0.00
93,Cenotaph Road,600018,2018-01-01,87,0.21,87,20000.00,22000.000000,22000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,0,0.00
94,Cenotaph Road,600018,2018-04-01,87,0.21,86,20000.00,22000.000000,22000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,1,0.00
95,Cenotaph Road,600018,2018-07-01,82,0.21,80,20000.00,22000.000000,22000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,2,0.00
96,Cenotaph Road,600018,2018-10-01,75,0.19,72,20000.00,22000.000000,22000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,3,0.00
97,Cenotaph Road,600018,2019-01-01,68,0.18,63,20000.00,22000.000000,22000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,3,0.01
98,Cenotaph Road,600018,2019-04-01,57,0.15,48,20000.00,22000.000000,22000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,3,0.00
99,Cenotaph Road,600018,2019-07-01,49,0.12,44,20000.00,22000.000000,22000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,2,0.00
100,Cenotaph Road,600018,2019-10-01,44,0.12,39,20000.00,22000.000000,22000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,1,0.00
101,Cenotaph Road,600018,2020-01-01,42,0.12,38,20000.00,22000.000000,20666.666667,0,...,0.01,0.97,0.0,0.02,0,0,0,1,0,0.00
121,Teynampet,600018,2012-04-01,71,0.12,45,12000.00,12000.000000,12000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,2,0.00
122,Teynampet,600018,2012-07-01,66,0.09,65,12000.00,12000.000000,12000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,1,0.00
123,Teynampet,600018,2012-10-01,62,0.09,61,12000.00,12000.000000,12000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,1,0.00
124,Teynampet,600018,2013-01-01,54,0.09,39,12000.00,13000.000000,13000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,4,0.00
125,Teynampet,600018,2013-04-01,46,0.07,34,12000.00,13000.000000,13000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,2,0.00
126,Teynampet,600018,2013-07-01,42,0.06,32,12000.00,13000.000000,13000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,0,0.00
127,Teynampet,600018,2013-10-01,38,0.06,23,12000.00,13000.000000,13000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,5,0.00
128,Teynampet,600018,2014-01-01,22,0.03,12,12000.00,13000.000000,13000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,4,0.00
129,Teynampet,600018,2014-04-01,13,0.02,7,12000.00,13000.000000,13000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,3,0.00
130,Teynampet,600018,2014-07-01,3,0.00,1,12000.00,13000.000000,13000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,2,0.00
131,Teynampet,600018,2014-10-01,0,0.00,0,12000.00,13000.000000,13000.000000,0,...,0.01,0.97,0.0,0.02,0,0,0,1,0,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8436,Kolapakkam,600074,2012-10-01,353,0.39,34,5000.00,4917.333333,4822.000000,25,...,0.03,0.92,0.0,0.05,0,0,0,1,63,0.09
8437,Kolapakkam,600074,2013-01-01,307,0.33,28,5000.00,4954.000000,4832.000000,0,...,0.03,0.92,0.0,0.05,0,0,0,1,20,0.03
8438,Kolapakkam,600074,2013-04-01,323,0.33,33,3800.00,4243.000000,4620.333333,5,...,0.03,0.92,0.0,0.05,0,0,0,1,17,0.01
8439,Kolapakkam,600074,2013-07-01,318,0.32,33,3800.00,4591.666667,4670.000000,0,...,0.03,0.92,0.0,0.05,0,0,0,1,12,0.00
8440,Kolapakkam,600074,2013-10-01,286,0.28,50,3800.00,4432.666667,4710.333333,0,...,0.03,0.92,0.0,0.05,0,0,0,1,8,0.00
8441,Kolapakkam,600074,2014-01-01,262,0.26,73,4843.77,4610.000000,4721.666667,6,...,0.03,0.92,0.0,0.05,0,0,0,1,12,0.01
8442,Kolapakkam,600074,2014-04-01,362,0.37,114,4440.00,4651.333333,4716.666667,24,...,0.03,0.92,0.0,0.05,0,0,0,1,39,0.03
8443,Kolapakkam,600074,2014-07-01,843,0.81,94,4440.00,4519.333333,4595.000000,0,...,0.03,0.92,0.0,0.05,0,0,0,1,56,0.06
8444,Kolapakkam,600074,2014-10-01,694,0.67,58,4440.00,4605.666667,4632.333333,0,...,0.03,0.92,0.0,0.05,0,0,0,1,39,0.03
8445,Kolapakkam,600074,2015-01-01,592,0.57,43,4440.00,4582.000000,4661.333333,0,...,0.03,0.92,0.0,0.05,0,0,0,1,26,0.03
8446,Kolapakkam,600074,2015-04-01,583,0.59,44,4800.00,4723.666667,4707.666667,10,...,0.03,0.92,0.0,0.05,0,0,0,1,40,0.04
8447,Kolapakkam,600074,2015-07-01,606,0.63,52,5500.00,4871.666667,4817.666667,9,...,0.03,0.92,0.0,0.05,0,0,0,1,42,0.05
8448,Kolapakkam,600074,2015-10-01,687,0.85,55,5500.00,5202.333333,4994.000000,0,...,0.03,0.92,0.0,0.05,0,0,0,1,33,0.05
8449,Kolapakkam,600074,2016-01-01,1434,1.74,110,5074.75,5082.666667,5043.000000,43,...,0.03,0.92,0.0,0.05,0,0,0,1,101,0.13
8450,Kolapakkam,600074,2016-04-01,1659,1.97,80,5074.75,5221.666667,5007.000000,0,...,0.03,0.92,0.0,0.05,0,0,0,1,71,0.10
8451,Kolapakkam,600074,2016-07-01,1431,1.69,60,5074.75,5034.666667,5021.000000,0,...,0.03,0.92,0.0,0.05,0,0,0,1,80,0.09
8452,Kolapakkam,600074,2016-10-01,1216,1.44,49,5074.75,4964.333333,5029.333333,0,...,0.03,0.92,0.0,0.05,0,0,0,1,42,0.05
8453,Kolapakkam,600074,2017-01-01,1110,1.32,53,5074.75,4837.000000,5056.333333,0,...,0.03,0.92,0.0,0.05,0,0,0,1,33,0.03
8454,Kolapakkam,600074,2017-04-01,1013,1.22,57,5074.75,4696.333333,5126.333333,0,...,0.03,0.92,0.0,0.05,0,0,0,1,37,0.04
8455,Kolapakkam,600074,2017-07-01,949,1.19,74,6440.00,5251.333333,5311.333333,4,...,0.03,0.92,0.0,0.05,0,0,0,1,31,0.04
8456,Kolapakkam,600074,2017-10-01,923,1.22,78,6440.00,5085.333333,5401.666667,0,...,0.03,0.92,0.0,0.05,0,0,0,1,41,0.05
8457,Kolapakkam,600074,2018-01-01,918,1.20,70,5628.00,5260.000000,5381.666667,6,...,0.03,0.92,0.0,0.05,0,0,0,1,76,0.09
8458,Kolapakkam,600074,2018-04-01,999,1.27,64,4600.00,4920.666667,5293.000000,5,...,0.03,0.92,0.0,0.05,0,0,0,1,48,0.05
8459,Kolapakkam,600074,2018-07-01,1064,1.35,59,5000.00,4865.333333,5252.333333,2,...,0.03,0.92,0.0,0.05,0,0,0,1,59,0.06
8460,Kolapakkam,600074,2018-10-01,1018,1.33,48,6440.00,5085.666667,5419.333333,1,...,0.03,0.92,0.0,0.05,0,0,0,1,69,0.08
8461,Kolapakkam,600074,2019-01-01,855,1.15,40,6440.00,4978.000000,5492.666667,0,...,0.03,0.92,0.0,0.05,0,0,0,1,57,0.06
8462,Kolapakkam,600074,2019-04-01,711,0.99,36,6440.00,4812.333333,5577.666667,0,...,0.03,0.92,0.0,0.05,0,0,0,1,31,0.03
8463,Kolapakkam,600074,2019-07-01,631,0.90,37,6440.00,4882.333333,5639.666667,0,...,0.03,0.92,0.0,0.05,0,0,0,1,22,0.03
8464,Kolapakkam,600074,2019-10-01,560,0.82,45,6440.00,4798.000000,5733.333333,0,...,0.03,0.92,0.0,0.05,0,0,0,1,23,0.03
8465,Kolapakkam,600074,2020-01-01,486,0.74,51,6440.00,5319.333333,5799.666667,0,...,0.03,0.92,0.0,0.05,0,0,0,1,20,0.02

In [79]:
markets = dset3['MicroMarket'].unique()

In [8]:
%matplotlib notebook

import matplotlib.pyplot as plt

In [35]:
from statsmodels.tsa.arima_model import ARIMA

In [39]:
from statsmodels.tsa.arima_model import ARIMA
import pmdarima as pm

In [155]:
from statsmodels.tsa.vector_ar.vecm import coint_johansen

In [9]:
markets=['Cenotaph Road', 'Teynampet', 'Ambattur Ind.Estate', 'Aminijkarai',
       'Anna Nagar', 'Balaji Nagar', 'Anna Salai', 'Mahindra World City',
       'Ayanavaram', 'Besant Nagar', 'Chromepet',
       'Purasawalkam', 'Egmore', 'Gopalapuram', 'Kalavakkam',
     'Rajakilpakkam', 'Camp Road', 'Selaiyur',
       'K.K Nagar', 'Kilpauk', 'Medavakkam', 'Kodambakkam',
       'Ottiambakkam', 'Madipakkam', 'Kancheepuram', 'Mandaveli',
       'Mylapore', 'Nandambakam', 'Ramapuram', 'Nanganallur',
       'Nungambakkam', 'Perambur', 'R A Puram', 'MRC Nagar', 'Roya Puram',
       'Royapettah', 'Pudupakkam', 'Saidapet', 'T. Nagar', 'Lakshmipuram',
       'Tambaram', 'Thirumangalam', 'Thiruvanmiyur', 'Neelankarai',
       'Palavakkam', 'Vadapalani', 'Velachery', 'Vepery',
       'Virugambakkam', 'Adyar', 'Indira Nagar', 'Adambakam', 'Padi',
       'Perungudi', 'Tharamani', 'Mogappair', 'Ashok Nagar', 'East Coast Road', 'Sholinganallur',
       'Semmancherry', 'Arasankazhani', 'Uthandi', 'karapakkam',
       'Pallavaram', 'Nanmangalam', 'Keelakattalai', 'Manikandan Nagar',
       'Manimangalam', 'Thoraipakkam', 'Mahabalipuram', 'Porur',
       'Sriperumbudur', 'Thirumullaivoyal', 'Padur', 'Thalambur',
       'Egattur', 'Siruseri SIPCOT', 'Alandur', 'Mambalam', 'Choolaimedu',
       'Tondiarpet', 'Vinayagapuram', 'Saligramam', 'Maraimalai Nagar',
       'Koyambedu', 'Injambakkam', 'Poonamalle', 'Kattupakkam',
       'Madhavaram', 'Kotturpuram', 'Tiruvallur', 'Pallikaranai',
       'Shantosapuram', 'Perumbakkam', 'Guindy', 'Ekkatuthangal',
       'GST Road', 'Urapakkam', 'Padappai', 'Manapakkam',
       'Valasaravakkam', 'Kalpakkam', 'Vayalur', 'Perungalathur',
       'Chengalpattu', 'Kelambakkam', 'Vengaivasal Main RD',
       'Guduvancheri', 'Nellikuppam', 'Minjur', 'NH-5', 'Vanagaram',
       'Maduravoyal', 'Aynambakkam', 'Thiruverkkadu', 'Korattur',
       'Villivakkam', 'Vandalur', 'Nallambakkam', 'Mambakkam',
       'Mannivakkam', 'Ponmar', 'Rathinamangalam', 'Polachery',
       'Mudichur', 'Oragadam', 'Ayappakkam', 'Potheri',
       'Poonamallee High Road', 'Avadi', 'Ambattur', 'Thiruvidandhai',
       'Muttukadu', 'Kovalam', 'Chembarambakkam', 'Thirumudivakkam',
       'Kundrathur', 'Pattabiram', 'Thiruninravur', 'Thirumazhisai',
       'Tiruvottiyur', 'Singaperumal Koil', 'Iyappanthangal', 'Kovur',
       'Mangadu', 'Thiruporur', 'Anakaputhur', 'Kolathur', 'Vedanthangal',
       'Madambakkam', 'Ponneri', 'Perur',
       'Sunguvarchatram', 'Periyapalayam', 'Walajabad', 'Gerugambakkam',
       'Kolapakkam']

In [10]:
from statsmodels.tsa.vector_ar.var_model import VAR

In [27]:
pred = pd.DataFrame(columns=['open_stock_units', 'Unsold in units', 'overhang'])
actual = pd.DataFrame(columns=usable)
ls = []

In [28]:
for mar in markets:
    data = dset3[dset3['MicroMarket']==mar][usable]
    train = data[:int(0.9*(len(data)))][['open_stock_units', 'Unsold in units', 'overhang']]
    valid = data[int(0.9*(len(data))):]
    for i in range(len(valid)):
        ls.append(mar)
    model = VAR(endog=train)
    model_fit = model.fit()
    prediction = model_fit.forecast(model_fit.y, steps=len(valid))
    actual = actual.append(valid,ignore_index=True)
    pred = pred.append(pd.DataFrame(prediction,columns=['open_stock_units', 'Unsold in units', 'overhang']),ignore_index=True)
    
pred['MicroMarket']=ls

C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)

C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)

C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)

C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)

In [34]:
actual['Total Absorption in units'] = (actual['open_stock_units']-actual['Unsold in units'])
actual

,MicroMarket,open_stock_units,Unsold in units,overhang,Total Absorption in units
0,Cenotaph Road,44,43,39,1
1,Cenotaph Road,42,42,38,0
2,Teynampet,0,0,0,0
3,Teynampet,0,0,0,0
4,Teynampet,0,0,0,0
5,Teynampet,0,0,0,0
6,Ambattur Ind.Estate,784,769,78,15
7,Ambattur Ind.Estate,729,706,94,23
8,Ambattur Ind.Estate,658,639,97,19
9,Aminijkarai,12,12,12,0
10,Aminijkarai,10,8,8,2
11,Aminijkarai,6,6,6,0
12,Aminijkarai,6,6,6,0
13,Aminijkarai,6,6,6,0
14,Anna Nagar,1011,986,135,25
15,Anna Nagar,944,921,125,23
16,Anna Nagar,890,879,126,11
17,Anna Nagar,857,847,137,10
18,Anna Nagar,874,906,150,-32
19,Anna Nagar,874,838,100,36
20,Balaji Nagar,0,0,0,0
21,Balaji Nagar,0,0,0,0
22,Balaji Nagar,0,0,0,0
23,Anna Salai,287,280,98,7
24,Anna Salai,267,263,101,4
25,Anna Salai,261,261,119,0
26,Mahindra World City,1754,1687,68,67
27,Mahindra World City,1547,1479,58,68
28,Mahindra World City,1352,1289,54,63
29,Mahindra World City,1172,1120,51,52
...,...,...,...,...,...
674,Ponneri,882,864,109,18
675,Ponneri,829,811,121,18
676,Ponneri,768,745,112,23
677,Ponneri,697,675,98,22
678,Perur,118,71,4,47
679,Perur,16,5,0,11
680,Perur,0,0,0,0
681,Perur,0,0,0,0
682,Sunguvarchatram,333,333,297,0
683,Sunguvarchatram,333,333,285,0
684,Sunguvarchatram,333,333,283,0
685,Sunguvarchatram,333,333,111,0
686,Periyapalayam,3,3,3,0
687,Periyapalayam,3,3,3,0
688,Periyapalayam,3,3,3,0
689,Periyapalayam,3,3,2,0
690,Walajabad,128,124,102,4
691,Walajabad,119,117,98,2
692,Walajabad,109,105,87,4
693,Walajabad,98,94,76,4
694,Gerugambakkam,222,212,59,10
695,Gerugambakkam,187,176,47,11
696,Gerugambakkam,159,151,43,8
697,Gerugambakkam,131,120,35,11
698,Gerugambakkam,101,94,28,7
699,Kolapakkam,855,798,40,57
700,Kolapakkam,711,680,36,31
701,Kolapakkam,631,609,37,22
702,Kolapakkam,560,537,45,23
703,Kolapakkam,486,466,51,20

In [40]:
pred['Total Absorption in units'] = (pred['open_stock_units']-pred['Unsold in units'])
pred['Total Absorption in units']=pred['Total Absorption in units'].round()
pred = pred[['MicroMarket', 'open_stock_units', 'Unsold in units', 'overhang', 'Total Absorption in units']]
pred

,MicroMarket,open_stock_units,Unsold in units,overhang,Total Absorption in units
0,Cenotaph Road,39.344615,35.860563,32.046600,3.0
1,Cenotaph Road,26.803798,22.753314,17.512320,4.0
2,Teynampet,-0.061193,-0.155573,-0.271877,0.0
3,Teynampet,-0.329687,-0.451313,-0.591495,0.0
4,Teynampet,-0.646438,-0.768077,-0.890175,0.0
5,Teynampet,-0.949294,-1.061237,-1.152281,0.0
6,Ambattur Ind.Estate,762.625437,742.671092,66.811488,20.0
7,Ambattur Ind.Estate,714.382317,697.649730,69.009031,17.0
8,Ambattur Ind.Estate,684.837610,671.029460,72.939724,14.0
9,Aminijkarai,12.892253,14.063547,5.536252,-1.0
10,Aminijkarai,16.425157,17.767644,8.167961,-1.0
11,Aminijkarai,20.259837,21.374930,10.637354,-1.0
12,Aminijkarai,23.384987,24.253031,12.733044,-1.0
13,Aminijkarai,25.793538,26.465157,14.481944,-1.0
14,Anna Nagar,956.096407,884.378225,141.610691,72.0
15,Anna Nagar,802.640692,752.119673,138.308260,51.0
16,Anna Nagar,704.156969,667.656410,136.021695,37.0
17,Anna Nagar,641.873636,614.602467,134.406909,27.0
18,Anna Nagar,603.353745,582.158495,133.236989,21.0
19,Anna Nagar,580.413085,563.218191,132.362518,17.0
20,Balaji Nagar,9.565234,19.529615,1.968944,-10.0
21,Balaji Nagar,37.462247,45.781895,5.014027,-8.0
22,Balaji Nagar,61.106045,68.448153,8.641055,-7.0
23,Anna Salai,293.115779,306.662684,99.693624,-14.0
24,Anna Salai,331.063418,333.455551,114.715237,-2.0
25,Anna Salai,337.008411,335.582215,111.954066,1.0
26,Mahindra World City,1810.213100,1830.890759,77.455168,-21.0
27,Mahindra World City,1849.632406,1848.578192,75.952284,1.0
28,Mahindra World City,1843.537477,1846.597723,74.890022,-3.0
29,Mahindra World City,1845.321949,1847.204527,73.935582,-2.0
...,...,...,...,...,...
674,Ponneri,872.390427,843.747184,85.409848,29.0
675,Ponneri,796.142155,772.713583,83.861014,23.0
676,Ponneri,735.667944,717.906110,83.072213,18.0
677,Ponneri,690.391785,677.230348,82.718937,13.0
678,Perur,179.929628,172.655668,2.716652,7.0
679,Perur,162.181273,158.448399,8.258274,4.0
680,Perur,151.775035,148.382325,12.016357,3.0
681,Perur,142.524419,139.543164,14.786561,3.0
682,Sunguvarchatram,329.405656,332.345607,263.073221,-3.0
683,Sunguvarchatram,336.885426,339.770141,268.581978,-3.0
684,Sunguvarchatram,344.152484,346.999455,272.545217,-3.0
685,Sunguvarchatram,351.282455,354.033853,275.316263,-3.0
686,Periyapalayam,3.649348,3.227750,2.498924,0.0
687,Periyapalayam,3.796338,3.425942,2.339803,0.0
688,Periyapalayam,4.092232,3.698311,2.206555,0.0
689,Periyapalayam,4.324256,3.908249,2.081721,0.0
690,Walajabad,134.578350,125.484956,103.349053,9.0
691,Walajabad,113.111707,106.745468,92.460557,6.0
692,Walajabad,98.648999,93.691935,83.817291,5.0
693,Walajabad,87.507763,83.920157,76.708386,4.0
694,Gerugambakkam,245.898305,269.150145,66.921812,-23.0
695,Gerugambakkam,301.753172,313.131918,68.636248,-11.0
696,Gerugambakkam,330.660803,339.015663,69.395529,-8.0
697,Gerugambakkam,351.134535,356.851902,69.519804,-6.0
698,Gerugambakkam,364.762937,368.827040,69.279825,-4.0
699,Kolapakkam,897.509905,885.813821,44.337241,12.0
700,Kolapakkam,834.589140,824.520716,44.287235,10.0
701,Kolapakkam,785.933943,780.681109,45.098877,5.0
702,Kolapakkam,754.474123,752.357307,46.438111,2.0
703,Kolapakkam,735.526714,735.683207,47.874637,-0.0

In [56]:
rmosu = (((pred['open_stock_units']-actual['open_stock_units'])**2).mean())**.5
print('rmse of open_stock_units: {}'.format(rmosu))

rmse of open_stock_units: 427.91414488722484

In [57]:
rmunu = (((pred['Unsold in units']-actual['Unsold in units'])**2).mean())**.5
print('rmse of Unsold in units: {}'.format(rmunu))

rmse of Unsold in units: 457.02810887456627

In [58]:
rmov = (((pred['overhang']-actual['overhang'])**2).mean())**.5
print('rmse of overhang: {}'.format(rmov))

rmse of overhang: 78.58927396180893

In [59]:
rmtau = (((pred['Total Absorption in units']-actual['Total Absorption in units'])**2).mean())**.5
print('rmse of Total Absorption in units: {}'.format(rmtau))

rmse of Total Absorption in units: 77.39171320449802

In [1]:
usable = ['MicroMarket','open_stock_units', 'Unsold in units', 'overhang']

In [2]:
usable

['MicroMarket', 'open_stock_units', 'Unsold in units', 'overhang']

In [60]:
index = ['2020Q2', '2020Q3', '2020Q4', '2021Q1', '2021Q2', '2021Q3', '2021Q4']
forecasted = pd.DataFrame(columns=['open_stock_units', 'Unsold in units', 'overhang'])
locs = []
for mar in markets:
    data = dset3[dset3['MicroMarket']==mar][['open_stock_units', 'Unsold in units', 'overhang']]
    for i in range(0,7):
        locs.append(mar)
    model = VAR(endog=data)
    model_fit = model.fit()
    prediction = model_fit.forecast(model_fit.y, steps=7)
    forecasted = forecasted.append(pd.DataFrame(prediction,columns=['open_stock_units', 'Unsold in units', 'overhang'],index=index))

C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)

C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)

C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)

C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)

C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)
C:\Users\Laptop\AppData\Roaming\Python\Python37\site-packages\statsmodels\tsa\base\tsa_model.py:214: ValueWarning: An unsupported index was provided and will be ignored when e.g. forecasting.
  ' ignored when e.g. forecasting.', ValueWarning)

In [61]:
forecasted['MicroMarket']=locs
forecasted = forecasted[['MicroMarket', 'open_stock_units', 'Unsold in units', 'overhang']]
forecasted['Total Absorption in units'] = forecasted['open_stock_units']-forecasted['Unsold in units']
forecasted

,MicroMarket,open_stock_units,Unsold in units,overhang,Total Absorption in units
2020Q2,Cenotaph Road,37.697931,36.043778,31.518793,1.654153
2020Q3,Cenotaph Road,31.653580,30.041965,24.658229,1.611615
2020Q4,Cenotaph Road,25.391166,23.737841,17.363445,1.653325
2021Q1,Cenotaph Road,18.817732,17.124082,9.637756,1.693650
2021Q2,Cenotaph Road,11.918178,10.181514,1.475304,1.736664
2021Q3,Cenotaph Road,4.673536,2.891359,-7.134292,1.782177
2021Q4,Cenotaph Road,-2.935342,-4.765583,-16.205152,1.830241
2020Q2,Teynampet,-0.050056,-0.127258,-0.222395,0.077202
2020Q3,Teynampet,-0.269813,-0.369503,-0.484419,0.099690
2020Q4,Teynampet,-0.529494,-0.629266,-0.729456,0.099772
2021Q1,Teynampet,-0.777903,-0.869690,-0.944372,0.091787
2021Q2,Teynampet,-0.997717,-1.079400,-1.127200,0.081683
2021Q3,Teynampet,-1.185518,-1.257331,-1.280407,0.071812
2021Q4,Teynampet,-1.343234,-1.406235,-1.407809,0.063001
2020Q2,Ambattur Ind.Estate,617.273989,615.995763,95.654360,1.278226
2020Q3,Ambattur Ind.Estate,624.631252,622.302787,96.504497,2.328466
2020Q4,Ambattur Ind.Estate,627.020774,624.737092,96.700890,2.283682
2021Q1,Ambattur Ind.Estate,628.627028,626.267599,96.705408,2.359429
2021Q2,Ambattur Ind.Estate,629.608233,627.171740,96.628052,2.436493
2021Q3,Ambattur Ind.Estate,630.216169,627.710326,96.529570,2.505843
2021Q4,Ambattur Ind.Estate,630.593948,628.031439,96.436270,2.562509
2020Q2,Aminijkarai,7.269851,8.857655,7.755055,-1.587804
2020Q3,Aminijkarai,12.418279,13.920481,10.242145,-1.502202
2020Q4,Aminijkarai,17.063795,18.224257,12.438745,-1.160462
2021Q1,Aminijkarai,20.614278,21.471925,14.228265,-0.857647
2021Q2,Aminijkarai,23.241066,23.872641,15.673014,-0.631575
2021Q3,Aminijkarai,25.194028,25.662995,16.850469,-0.468967
2021Q4,Aminijkarai,26.671523,27.023370,17.822814,-0.351847
2020Q2,Anna Nagar,901.867750,930.422570,100.621749,-28.554820
2020Q3,Anna Nagar,990.194536,1009.536909,100.953610,-19.342373
...,...,...,...,...,...
2021Q3,Sunguvarchatram,314.301008,314.420152,211.374914,-0.119144
2021Q4,Sunguvarchatram,315.115354,315.476362,216.748298,-0.361008
2020Q2,Periyapalayam,4.001397,3.711030,1.949791,0.290367
2020Q3,Periyapalayam,4.178696,3.859514,1.849713,0.319182
2020Q4,Periyapalayam,4.276258,3.945102,1.752248,0.331155
2021Q1,Periyapalayam,4.341958,4.001924,1.659876,0.340033
2021Q2,Periyapalayam,4.384535,4.037525,1.572419,0.347011
2021Q3,Periyapalayam,4.409328,4.056818,1.489583,0.352510
2021Q4,Periyapalayam,4.420463,4.063622,1.411095,0.356841
2020Q2,Walajabad,87.101947,86.104497,71.506065,0.997450
2020Q3,Walajabad,84.294467,83.479780,69.221029,0.814687
2020Q4,Walajabad,81.828093,81.414765,67.356263,0.413328
2021Q1,Walajabad,80.324858,80.195431,66.020113,0.129427
2021Q2,Walajabad,79.483759,79.569413,65.101606,-0.085654
2021Q3,Walajabad,79.137737,79.376487,64.517649,-0.238750
2021Q4,Walajabad,79.137112,79.478802,64.190255,-0.341690
2020Q2,Gerugambakkam,108.000461,137.892856,35.389814,-29.892396
2020Q3,Gerugambakkam,180.745590,197.944230,40.274007,-17.198640
2020Q4,Gerugambakkam,224.721879,238.575090,44.033314,-13.853211
2021Q1,Gerugambakkam,259.087212,269.511289,46.837451,-10.424077
2021Q2,Gerugambakkam,284.477363,292.485014,48.944428,-8.007651
2021Q3,Gerugambakkam,303.446979,309.630096,50.527021,-6.183117
2021Q4,Gerugambakkam,317.585264,322.410433,51.717386,-4.825169
2020Q2,Kolapakkam,499.138702,523.680802,53.827717,-24.542100
2020Q3,Kolapakkam,574.356306,588.551851,57.118359,-14.195546
2020Q4,Kolapakkam,626.637512,637.947135,58.106622,-11.309623
2021Q1,Kolapakkam,666.427756,674.139170,58.013722,-7.711414
2021Q2,Kolapakkam,693.328250,698.249568,57.297827,-4.921318
2021Q3,Kolapakkam,709.871985,712.697185,56.339022,-2.825200
2021Q4,Kolapakkam,718.613150,720.005198,55.369208,-1.392048

In [62]:
forecasted.to_excel('Forecast.xlsx')